### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Scope666** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#1]
Hey, just wanted to thank you for posting this.  I just built up a similar rig but with the Asus Strix Z490-E motherboard.  I'm going to attempt to follow your procedure and see how I make out.

I'm brand new to OpenCore so there will some learning necessary there.  I've been using Clover for years.

**Comment by Scope666** [comment]
Ok, so I gave it a shot, I'm guessing there's something different enough, guessing maybe USB ports that's making it hang here:

![image](https://user-images.githubusercontent.com/31927547/82772545-713fee00-9e0d-11ea-9324-4880a448447d.png)

**Comment by SchmockLord** [comment]
Try it without NVMeFix.kext again

**Comment by Scope666** [comment]
Thanks for the reply, I set NVMeFix.kext to disabled, it's hanging in a different place now:

![image](https://user-images.githubusercontent.com/31927547/82819211-01158480-9e6e-11ea-94db-51bd884a8d92.png)

**Comment by Scope666** [comment]
Made some progress, now I have to work around the Intel i225-v ethernet not being supported.

![image](https://user-images.githubusercontent.com/31927547/82832833-4a73cd00-9e8a-11ea-8cc5-410c85154146.png)

**Comment by Scope666** [comment]
Well, it took a LOT of work but I got it up and running!

![image](https://user-images.githubusercontent.com/31927547/82837774-0f789600-9e98-11ea-9948-114d2cbfaf66.png)

**Comment by ssijak** [comment]
Thank you to both of you. I was waiting for z490 reports so I can finally decide if I should buy z390 + 9900k or z490 + 10900k. I'll go with the later now.

**Comment by Scope666** [comment]
Can't go wrong, it's a great chip.  It's actually running cooler than my 7700K did, and that only was a 4/8 chip, this thing is 10/20.     :-)

**Comment by SchmockLord** [comment]
You are all welcome :)

**Comment by neilpanchal** [comment]
@Scope666 Could you please share your Opencore configuration/EFI folder? Very much appreciated!

**Comment by Jimbojingle** [comment]
Thanks for your hard work. I was waiting to try out the same hardware so this has saved a whole lot of effort. What make of Radeon VII did you use in your build?

**Comment by Scope666** [comment]
> @Scope666 Could you please share your Opencore configuration/EFI folder? Very much appreciated!

Sure, I have a copy here, it's by no means perfect... still tweaking but most things are working:

https://www.tonymacx86.com/threads/gigabytes-z490-motherboard-lineup-shows-up-early.296353/post-2129452

**Comment by bakatest-me** [comment]
Thanks :)

**Comment by pengin** [comment]
Hi. I've also succeeded to build hackintosh on Z490-Vision-D, i7 10700 and RX5700XT. Your EFI is perfectly working.
 I still have tiny problems (somehow DPs on VGA are not working, I have confirmed TB3s are working...etc) but those are out of scope.

Anyway, Thank you so much.

**Comment by bakatest-me** [comment]
@pengin  can i ask you a bit about RX5700xt? i use RX5700xt too. Have you success to set hardware accel?
![Screen Shot 2563-05-31 at 13 50 35](https://user-images.githubusercontent.com/22494087/83346380-f82d2300-a345-11ea-97a8-8fb678168dae.png)

**Comment by pengin** [comment]
@bakatest-me 
I do not know your software to show the hardware information but my hackintosh can recognize the RX5700XT card. Also I got reasonable scores of it from Geekbench 5, that means radeonboost and drivers is fully working.

By the way, your problem may depends on applications not hackintosh's settings. Adobe Lightroom (Adobe camera raw) also can recognize my RX5700XT as you can see in my 3rd screenshot (sry in Japanese) however VideoProc can not as you.

![ss1](https://user-images.githubusercontent.com/2162454/83349777-5d970900-a372-11ea-98ed-8b31d7983da9.png)

![ss2](https://user-images.githubusercontent.com/2162454/83349778-6091f980-a372-11ea-881d-aadf2b1c0496.png)

![ss3](https://user-images.githubusercontent.com/2162454/83349925-473d7d00-a373-11ea-92e0-3871ea0378a2.png)

**Comment by bakatest-me** [comment]
> @bakatest-me
> I do not know your software to show the hardware information but my hackintosh can recognize the RX5700XT card. Also I got reasonable scores of it from Geekbench 5, that means radeonboost and drivers is fully working.
> 
> By the way, your problem may depends on applications not hackintosh's settings. Adobe Lightroom (Adobe camera raw) also can recognize my RX5700XT as you can see in my 3rd screenshot (sry in Japanese) however VideoProc can not as you.
> 
> ![ss1](https://user-images.githubusercontent.com/2162454/83349777-5d970900-a372-11ea-98ed-8b31d7983da9.png)
> 
> ![ss2](https://user-images.githubusercontent.com/2162454/83349778-6091f980-a372-11ea-881d-aadf2b1c0496.png)
> 
> ![ss3](https://user-images.githubusercontent.com/2162454/83349925-473d7d00-a373-11ea-92e0-3871ea0378a2.png)

it's okay :) thanks.

**Comment by bakatest-me** [comment]
@pengin  thanks. i have can't add radeonboot.ketx in EFI (can't boot)  Can you share your EFI?

**Comment by pengin** [comment]
@bakatest-me 
My EFI is same as this repository except for boot-args in config.plist. Of course as you know, Rx5700XT needs "agdpmod=pikera" and I just changed it. Have you tryed some SSDT patch that have the same functionality as radeonboost? That will likely work fine.
