### ISSUE TITLE
Update to 0.6.4 producing blank screen with FileVault enabled

### ISSUE THREAD

**Issue by g3d** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#105]
Tried to update to the new version just as I usually do (extract EFi, rename config (iGPU compute only) change MLB, Serial, SystemUUID, save & reboot).

Bootloader loads, ask for FileVault password but after entering it nothing happens. 0.6.3 working like a charm.
Right now I'm trying to disable FileVault to ensure the problem is related to FileVault specifically.

Did anyone else observe that problem as well?

**Comment by SchmockLord** [comment]
Maybe try it with SIP enabled: csr-active-status to <00000000>

**Comment by SchmockLord** [comment]
Try it again. Maybe it was due to #106

**Comment by g3d** [comment]
Waiting for process to be finished & would verify this assumption.

![](https://files.g3d.codes/Screen-Shot-2020-12-09-19-24-53.png)

**Comment by g3d** [comment]
Observe the same behavior even with FileVault disabled, I believe that can be closed as a duplicate of #108
