### ISSUE TITLE
USBInjectAll Missing from 0.6.4 release Download

### ISSUE THREAD

**Issue by MidnightDiner** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#106]
Hey, just so you know USBInjectAll is in the config.plist, but it was missing from the kexts folder. Everything started working again once I added the USBInjectAll.kext back to the kexts folder. Thanks for doing all this great work!

**Comment by SchmockLord** [comment]
Thanks for pointing that out. Just fixed it. Can you please check current release again?
