### ISSUE TITLE
Just curious: Why remove the "RX 5700 XT-Version 1.0.aml" ? 

### ISSUE THREAD

**Issue by stimw** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#109]
As far as I know, It's used to improve 5700xt.
But after you removed it in the latest EFI, I found that the 5700xt get the same performance.
Does that mean we don't need it anymore?

**Comment by SchmockLord** [comment]
Yeah, it seems it is not necessary anymore. I made the same experience under Big Sur.
