### ISSUE TITLE
Bootup stops at graphics glitch with the "Prohibited" sign

### ISSUE THREAD

**Issue by Twixes** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#110]
This config is some great work, but unfortunately I'm stuck: Catalina bootup stops for me at the below point. Then after a moment or so the text glitches out graphically and the "Prohibited" sign appears. Nothing more then happens, except the screen periodically glitches out differently.

![392671D2-63F8-4A4B-A496-AD9F452D6A9E_1_105_c](https://user-images.githubusercontent.com/4550621/102060546-9ff5d400-3df2-11eb-9d06-cad109dab322.jpeg)

This suggests to me some sort of dGPU issue (as that's what I'm using for display), but with no relevant debug messages I'm not sure. Maybe one of you have seen something like this?

My specs:
Vision D
i7-10700K
RX 5700 XT
(the build also has a WD M.2 SSD and a Samsung M.2 SSD if that's relevant)

Running the EFI folder from the latest release of this repo verbatim, changed nothing except renamed `config_iMac20,2_iGPU_computing_only.plist` to `config.plist` and used `GenSMBIOS` on it to for a new random `iMac20,2` identity.

**Comment by Nishant-Kathil** [comment]
try the 3.9 release of the EFI folder. I think that clean

**Comment by Twixes** [comment]
I changed some BIOS settings and this started working! Almost sure it was about graphics, but I'm not sure what setting was relevant exactly. If anyone else gets this same issue, maybe I'll be able to compare BIOS settings and point something out there. Closing the issue.
