### ISSUE TITLE
Overclock

### ISSUE THREAD

**Issue by FataZlity** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#111]
Can you share your overclock settings? I know it's "personal" but for reference please.

**Comment by SchmockLord** [comment]
My Overclock settings now are:

Per Core overclocking: 53 when 2 cores are utilized 52 when 6 cores are utilized 51 with more than 6 cores are utilized
voltage offset: -50mV
Short Term Power Limit: 250W
Long Term Power Limit: 250W
