### ISSUE TITLE
Some apps not working

### ISSUE THREAD

**Issue by samuel21119** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#12]
I have built a hackintosh with i9-10900 + Z490 Vision-G, taking your EFI as an example. Most of the systems are working, but I found that when opening firefox, it'll crash. And I discovered that when running windows 10 vm on VM Ware Fusion 15, it'll crash too. Can you test with your system?

**Comment by SchmockLord** [comment]
Have you disabled VT-D in BIOS?

Maybe that is causing the issue.

**Comment by samuel21119** [comment]
I disabled it, but still not working.

**Comment by samuel21119** [comment]
After install AMD R9 380 with acpi spoof id, the problems disappeared. It seems that macOS stills have some problem dealing comet-lake-s iGPU.
