### ISSUE TITLE
Can't get Apple Watch Unlock to work with Fenvi Card on Big Sur 11.1

### ISSUE THREAD

**Issue by wkruddy** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#126]
OS: Big Sur 1.1
OC Vers: 0.6.4

I installed the Fenvi card suggested in the README. It originally sent my my computer into disarray and I was afraid it fried my Mobo... After a few hours of Error 99, A6, and A2 error codes, countless reboots with no BIOS, unplugging and reseating everything in multiple configurations and it _finally_ booted... to BIOS and I was able to get it back online. Scared me for a moment that the Fenvi card legit ruined my Mobo (it doesn't sit perfectly in the socket, like it's a little long on the connecting bar, so it might jiggle around)

So, this build feels fragile AF, worried to turn it off at this rate! 

But everything seems to be running great; albeit my display output doesn't run the native 3440x1440 of my monitor after upgrading from Catalina on the iGPU, but that's for another day I guess..

Anyway, for this issue:

I didn't have to remove HS14 using Hackintool for Intel BT to get removed- just straight up wasn't there?.. But the Fenvi card suggested seems to be working fine out of the box: I have Wifi, I have Bluetooth things connected to it, etc.

I've followed all of Apple's steps, have the right Watch and OS versions, 2FA, BT/Wifi on the watch work, all the stuff they seem to require... but when I click on the "Use your Apple Watch to unlock apps and your Mac" it just hangs on "Turning on..." then eventually fails.

Has anybody else had an experience like this? 

I'm using `iMac 20,2_iGPU_with_display_output.plist` with my SMBIOS stuff copied in, but pretty much stock otherwise. Is this just something that is going to be a caveat of this Hack? Would kind of be a bummer. 

I can only think of two possible scenarios:
- Because HS14 wasn't there, there's some weird conflict? but then why would other BT items work just fine?
- I used the first of my generated UUID/Serial/etc which seemed to be fine (all iServices work out of the box with no issue) but even though the About This Mac says it's a fancy iMac, and when I go into `Hackintool > System > System Tab` states it's a fancy iMac... the `System > Serial Tab` info if a little iffy?

It says it has a different serial (from 2006) and is a 13" MBP. but `Hackintool > System > System Tab > Serial Info` says 
```
Year 2010
Model ???
Model Identifier ???
Valid Possibly
```
So, would it be possible that these conflicting things could be the culprit, or just red herrings? Should I attempt OC 0.6.5?

Thanks!

**Comment by RobyRew** [comment]
my display also its not working at full res 3840 x 1600, i have it running only at 2560 x 1080, i have tried every hackintool connfiguration and i don't have any result.

But my Laptop with hackintosh its working nice a laptop with a 2018 CPU
https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_Updated_OpenCore

**Comment by SchmockLord** [comment]
Try this: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#apple-watch-unlock-issues

And this: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by wkruddy** [comment]
@SchmockLord Did not even notice this part of Dortania's. Thanks! Will report back and close ticket if it fixes it.

**Comment by wkruddy** [comment]
@SchmockLord I had to do the aforementioned things multiple times and reboot- nothing worked... Until I randomly got a notification today saying, "Hey you can unlock your Mac with your watch, want to try?" and then it started working. Thanks for pointing me this direction.
