### ISSUE TITLE
Conflict in PCI Path for Intel i225-V Device Property

### ISSUE THREAD

**Issue by 5T33Z0** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#127]
Upon checking my config with OC validate I noticed an error in the PCI path for the Intel i225-V Device Property.

The path in config is: PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0, 0x0)

According to OC Validate the correct form is: PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0) 

So without the space between 0x0, 0x0

Greetings

**Comment by SchmockLord** [comment]
Have you tried that? Last time I tried to correct this in the config.plist, people were having issues.

**Comment by Nelbjo** [comment]
I have adjusted as above (w/o the space) and it works for me. Using LAN via i225-V.

**Comment by 5T33Z0** [comment]
I have the Vision G Board which uses the same Intel i225-V chip. Working fine with the corrected path.

**Comment by g3d** [comment]
Works without space

**Comment by mauticom** [comment]
Works without space here too.
