### ISSUE TITLE
Update failed from 4.1 to 4.4

### ISSUE THREAD

**Issue by irodeanu** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#139]
I successfully did a build with version 4.1 in December, everything works ok.

Today I tried to update, I mounted EFI and I replaced it with the newest version of EFI besides config.plist.

I attach the result in the picture. 

![IMG_6599](https://user-images.githubusercontent.com/5019858/107516688-702a3900-6bb5-11eb-80cd-da51e7676759.jpg)

**Comment by g3d** [comment]
> I replaced it with the newest version of EFI besides config.plist.

You need to have an updated config.plist. When you do update, pick up config.plist from the repo and put your MLB, Serial, SystemUUID from the old config).

Each OpenCore update introduces corresponding changes for the config.plist, so you have to perform update correctly, as keeping the old config.plist would not work for obvious reasons.

**Comment by irodeanu** [comment]
> > I replaced it with the newest version of EFI besides config.plist.
> 
> You need to have an updated config.plist. When you do update, pick up config.plist from the repo and put your MLB, Serial, SystemUUID from the old config).
> 
> Each OpenCore update introduces corresponding changes for the config.plist, so you have to perform update correctly, as keeping the old config.plist would not work for obvious reasons.

Solved, thanks for the advice!
