### ISSUE TITLE
Stuck starting installer "apfs_module_stop:1730"

### ISSUE THREAD

**Issue by sebastienb** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#14]
First of all thanks for starting this repo! I'm building a machine with similar specs with the only difference being that I'm using a gigabyte 5700xt. When I try to run the osx installer I get this error:

apfs_module_stop:1730

I built my EFI from open core download and also tried your EFI and have the same issue. I already added `agdpmod=pikera` to my boot_args thinking that would solve it but no luck.

![F31CACD4-9B34-49C0-95DF-61582C40B326_1_105_c](https://user-images.githubusercontent.com/2538981/83932302-a3d3da00-a76f-11ea-8adb-c22155dce768.jpeg)

**Comment by CoolHamster28** [comment]
how did you resolve?  I'm experiencing the same problem

**Comment by sebastienb** [comment]
I clears
My efi folder completely and use the one on this repo replacing only the computer info, motherboard info and serial number and it booted and installed. I think I had some bad files in my previous efi folder.
