### ISSUE TITLE
Incredibly Slow Boot with iGPU Enabled.

### ISSUE THREAD

**Issue by gtrooper** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#142]
Hello,

This EFI works amazingly well with only a small caveat... When I enable iGPU in BIOS, boot is extremely slow. When I disable iGPU boot is incredibly fast. I am using config.plist with display output. I need iGPU for Sidecar. Anyone else with iGPU enabled that does not have this issue ?

**Comment by Got99** [comment]
Compu....

发自我的 iPhone

在 2021年2月23日，18:00，gtrooper <notifications@github.com<mailto:notifications@github.com>> 写道：


Hello,

This EFI works amazingly well with only a small caveat... When I enable iGPU in BIOS, boot is extremely slow. When I disable iGPU boot is incredibly fast. I am using config.plist with display output. I need iGPU for Sidecar. Anyone else with iGPU enabled that does not have this issue ?

**Comment by jamesfawcett** [comment]
Mine is also very slow to boot with iGpu enabled

**Comment by Got99** [comment]
Please use  config_iMac20,2_iGPU_computing_only.plist

**Comment by gtrooper** [comment]
> Please use config_iMac20,2_iGPU_computing_only.plist

I just used config_iMac20,2_iGPU_computing_only.plist but the iGPU does not appear in hackintool in the System-Peripheral section. In PCIe section at the Device Name I get "Intel ???" . Is this normal ? Does the iGPU actually works as computing only even when Hackintool does not show it properly ? Thank you Got99 !!!

**Comment by Got99** [comment]
Please use VideoProc to test

**Comment by gtrooper** [comment]
> Please use VideoProc to test

I just did and here is a screenshot inside VideoProc.

<img width="934" alt="VP" src="https://user-images.githubusercontent.com/43722469/108854185-3fec8c80-75f0-11eb-8e6b-f621231528bb.png">

It seems that iGPU gets recognized properly. Is that the case ?

**Comment by Got99** [comment]
yes

**Comment by gtrooper** [comment]
> yes

A HUGE thanks for your help Got99 ! Hugely appreciated ! I hope the best for you, especially these hard times !

**Comment by addisonduda** [comment]
> > Please use config_iMac20,2_iGPU_computing_only.plist
> 
> I just used config_iMac20,2_iGPU_computing_only.plist but the iGPU does not appear in hackintool in the System-Peripheral section. In PCIe section at the Device Name I get "Intel ???" . Is this normal ? Does the iGPU actually works as computing only even when Hackintool does not show it properly ? Thank you Got99 !!!

I have the same thing showing up. I mentioned in another issue that the Device ID is missing and shows the "???" in Hackintool. I mentioned how I added the Device ID in that issue if you'd like to take a look. It should still be working properly, just missing the name.

**Comment by gtrooper** [comment]
> > > Please use config_iMac20,2_iGPU_computing_only.plist
> > 
> > 
> > I just used config_iMac20,2_iGPU_computing_only.plist but the iGPU does not appear in hackintool in the System-Peripheral section. In PCIe section at the Device Name I get "Intel ???" . Is this normal ? Does the iGPU actually works as computing only even when Hackintool does not show it properly ? Thank you Got99 !!!
> 
> I have the same thing showing up. I mentioned in another issue that the Device ID is missing and shows the "???" in Hackintool. I mentioned how I added the Device ID in that issue if you'd like to take a look. It should still be working properly, just missing the name.

I just discovered your other issue but I noticed that on my config_iMac20,2_iGPU_computing_only.plist the device id is NOT missing... it is Device ID C59B0000. If I change this to the one you mention Device ID 923E0000, I get the NAME PROPERLY on Hackintool. But Do we really require to make this change ? It seems to be working properly with both Device-id's but I am sure there must be a more "proper" one. What do you think ?

**Comment by hacker1024** [comment]
On my Asus Z87-C, enabling display output through the iGPU also slows boot down significantly. I need to use it as I don't have enough ports on my dGPU. Has anyone found a real solution to this problem?

**Comment by gtrooper** [comment]
> On my Asus Z87-C, enabling display output through the iGPU also slows boot down significantly. I need to use it as I don't have enough ports on my dGPU. Has anyone found a real solution to this problem?

No.. and probably will never be a real solution. You need to use Device ID 923E0000 because this is the proper value for Desktop iGPU. If you use Device ID C59B0000, you will encounter issues with SideCar. Your best option is to use iGPU for Computing Only config. There is a finally a way for those people who use AMD 5000-6000 GPU's to make Sidecar work with NO iGPU at all which is amazing news ! 

More on that: https://github.com/acidanthera/FeatureUnlock
