### ISSUE TITLE
Will this work with AMD 6800XT? If not, when will we have it? (Fixed - It's work on BigSur 11.4)

### ISSUE THREAD

**Issue by huukhai1703** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#155]
Hi there,

Thanks a lot for your hard work on this. I just purchased the 6800XT for gaming. Your EFI worked perfectly with my previous build (5700XT) but i plug the new card and the OS stuck on the boot load. 

Can you guys let me know when mac OS will support this card? I heard that on the macOS 11.3 apple bring new driver for AMD 6000 card

**Comment by g3d** [comment]
That heavily depends on Apple and there is no guarantee it would work.
The latest update I saw for this was the end of previous year: https://dortania.github.io/hackintosh/updates/2020/11/17/navi20.html
Didn't saw any progress since that post

**Comment by huukhai1703** [comment]
Hi all,

Just a new great updated NEW. You guys can now use AMD VGA 6800XT on the macOS 11.4 Beta. I just did it on last weekend

Thanks all for you help 
![Uploading 176499783_4031837653548891_3311903086104514440_n.jpg…]()

**Comment by huukhai1703** [comment]
There are only. 1 problem that Apple TV that not working.
