### ISSUE TITLE
Intel I225 Fakepciid Kext no longer working in macOS Monterey

### ISSUE THREAD

**Issue by 5T33Z0** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#168]
Seems like the device ID fot the I225 NIC changed in macOS Monterey but I really can't wrap my head around it, since I don't know which of the devices listed in IO Regestry explorer is the I225 Controller. Unfortunately, this Kernel Patch mentioned in Dortanias Guide stopped working in 11.4  either: https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#kernel

**Comment by AvaQueen-Official** [comment]
I225-v is natively supported from 11.4 onwards; no need for the fakeid!

**Comment by 5T33Z0** [comment]
No, it is not - the I225-LM is, but not the V! I am using the Vision G Board which uses the same controller as the Vision D, so it is likeI explained above.

**Comment by kokowski** [comment]
> I225-v is natively supported from 11.4 onwards; no need for the fakeid!

How long are you running the i225-v without fakeid and kernel patch?

**Comment by 5T33Z0** [comment]
For 7 days, since my previous Post. Since then I changed the device-ID to F3158680 (DATA) which is the actual address of the Ethernet Controller on the Vision G which I am using and it works fine in Big Sur 11.4 without Kernel Patch. 

But it does not work in Monterey. The driver is loaded though, but internet just doesn't work. Might be a related to the beta status of Monterey, though.

**Comment by kokowski** [comment]
Thank you. And you @AvaQueen-Official how long do you manage this without fakeid or patch? Where did you get this information?

**Comment by SchmockLord** [comment]
Try the newest release. Should be fixed now.

**Comment by 5T33Z0** [comment]
With macOS Big Sur 11.4 onwards, you no longer need Device Properties to make this controller work. Instead, you can just use boot-arg `dk.e1000=0` to utilize the new DEXT Driver with this controller. Monterey may require manual assignment of the IP Address, though.

Check this Discussion for reference: https://github.com/dortania/bugtracker/issues/213

**Comment by Malumen** [comment]
FYI anyone struggling with Monterey onward try `e1000=0`
