### ISSUE TITLE
Thanks - Hackintosh working with i9 10900K and 2080 TI!

### ISSUE THREAD

**Issue by jamesfawcett** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#17]
Thank you for sharing your research! 

I had almost given up, I've tried Clover, OpenCore guide, Tony Mac and Unibeast.... the list goes on. I was at a dead end, until I saw your success this morning! I thought I would have to wait longer for more people to get matching hardware for working kexts and drivers.

I am running the MSI 2800 TI using the DisplayPort. I haven't yet tried HDMI output but DisplayPort is working great. The Cooler is doing it's job and kicking in when needed, all temperatures are good.

Windows 10 is installed on the first 1TB Nvme m.2 drive, Catalina is installed on the 2nd 500gb Nvme m.2 drive and dual boot is working flawlessly. 

Still to fix:
Front USB ports
Wifi - I have ordered a Fenvi T919 same as you.
Sound output - I haven't yet worked out how to change the address, but I have the same chipset as you I think, so I am researching that next.

Working: 
Rear USB ports
USB-C ports

My system is: 
Motherboard: Gbyte Z490 AORUS PRO AX Motherboard
Processor:  Intel Core i9 10900K overclocked to 5.1 Ghz
Ram:  2x8G CorVenRGBPRO DDR4 3000
GPU: MSI RTX 2080 Ti VENTUS GP OC
WIFI BT: TBC - not working yet
Storage: 2x  Samsung 1TB 970 EVO PLUS (windows 10 and Mac Catalina dual boot)
CPU cooler: iCueH150i
Case: NZXT H710 Black Mid Tower Case

![Photo 13-06-2020, 14 46 40](https://user-images.githubusercontent.com/5245272/84570728-40f1cc80-ad87-11ea-9063-27546bd2f827.jpg)
![Photo 13-06-2020, 14 16 24](https://user-images.githubusercontent.com/5245272/84570730-44855380-ad87-11ea-87f1-80869bd78ed9.jpg)
![Photo 13-06-2020, 14 13 51](https://user-images.githubusercontent.com/5245272/84570731-451dea00-ad87-11ea-8597-aec4cda631d3.jpg)
![Photo 13-06-2020, 14 11 52](https://user-images.githubusercontent.com/5245272/84570732-45b68080-ad87-11ea-8deb-e6056cfe161b.jpg)

**Comment by SchmockLord** [comment]
Congrats. Looks good.

For the USB just delete my SSDT-UIAC.aml. I am pretty sure this won't work so well with a different motherboard. Then you should see all USB-ports in Hackintool. Then delete all the ones you don't need until you reach the 15-port limit. Thunderbolt port doesn't count into the 15 port limit (e.g. SSP1, SSP2)

**Comment by SchmockLord** [comment]
You should also set the appropriate type: "USB2" for USB2-only ports. "USB3" for all ports that support USB2 and USB3 or USB3-only. "Type C" for USBC-ports where every direction has its own port. "Type C+SW" for USB-C ports where the same port lights up in both directions.

**Comment by SchmockLord** [comment]
And get an AMD graphics card. If you don't need much power, get an 5500XT for around 200 EUR. You can disable the 2080 Ti. 

BTW: You plugin your monitor into the 2080 Ti DisplayPort and use the iGPU? What is the highest resolution you can select? Can you post a picture of your "About this mac" screen?

**Comment by jamesfawcett** [comment]
Thanks very much! The 2080 TI graphics card is working well with Mac OS, I am using the displayport output, the same port I use for Windows 10. I'll get a screenshot of the about my mac later today. My monitor is running at 3440 x 1440. 

Thats a good tip about the USB ports I will give that a go thank you! Looking forward to the Wifi card arriving to get online!

I haven't used Hackintool yet, did you compile it from here? https://github.com/headkaze/Hackintool

**Comment by Scope666** [comment]
The 2080 Ti is not supported (I have one also). It may display text but you have no acceleration aka Metal support.  You can verify this by trying to watch a video on YouTube, use Mission Control or Launchpad, etc.

I solved this by adding an inexpensive RX 560:

https://www.asrock.com/Graphics-Card/AMD/Phantom%20Gaming%20Radeon%20RX560%204G/

I leave my 2nd monitor always plugged into it (works fine in Windows too) and just move my primary DisplayPort cable from the RX 560 to the 2080 Ti if I want to game in Windows.

**Comment by jamesfawcett** [comment]
Thanks for that! I may look at getting a secondary graphics card, but for now it seems to be working? Mission control and Launchpad works, I can play videos in Quicktime, Are there any other offline tests I can do until my WiFi card arrives? I am going to do a cleaner install, I rushed this one as a "last attempt" before giving up using @SchmockLord 's EFI. 

![Screenshot 2020-06-14 at 12 01 28](https://user-images.githubusercontent.com/5245272/84600571-1cbeea00-ae72-11ea-924b-28e53e3d679c.png)

Happy to buy a graphics card if I need to. Please tell me if I'm missing something major :)

I will try the HDMI ports and see the results too.

**Comment by Scope666** [comment]
The other way to tell is "About this Mac" --> "System Report..."  ... and look under Graphics.  There should be a place that says Metal support.

**Comment by jamesfawcett** [comment]
Excellent thanks @Scope666 

I am learning as much as I can, I have been a Mac user for years and not looked at PC Hardware since the early 2000's when I bought an AMD500Mhz machine! 

I've been reading about graphics cards all evening - I now understand how it's using the iGpu from the i9 processor. I am currently facing another issue, my motherboard has three PCI 16 slots, but If I put a graphics card into the PCI16 x8 slot next to my 2080 TI which is in a PCI16 x16 slot, it will slow it down to x8. I don't think I can physically fit a 5500XT or  RX 560 into the space available. 

I have been looking at compact, native supported graphics cards. I have come across the Nvidia GT710 - they're a bit old now, but have HDMI and passive cooling too to keep the noise down and would fit in the space where the PCI16 x4 slot is on my motherboard. 

Would you advise against these? Ill mostly be using just VSCode, Chrome and Spotify:
https://www.ebay.co.uk/itm/ASUS-NVIDIA-GeForce-GT-710-1GB-GDDR5-Graphics-Card-90YV0AL2-M0NA00/283914556542?epid=6010332194&hash=item421aa0547e:g:KDwAAOSwqQpe5PVH

Thanks for your help :)

**Comment by Scope666** [comment]
No kext loaded = no acceleration   (driver not loaded)

This is how I have my cards, I chose this RX 560 since it was smaller and didn't require more PCI-E power lines:

![IMG_1041](https://user-images.githubusercontent.com/31927547/84605490-a4edc100-ae6b-11ea-92c5-f1738a63a60b.jpg)

**Comment by jamesfawcett** [comment]
Nice setup!!! I am concerned about using that slot because it will force the 2080ti to x8, does your motherboard do that too? Have you noticed any performance loss?

**Comment by SchmockLord** [comment]
@jamesfawcett Why do you think you need a dGPU? 
If the power of the UHD630 is enough for you and you can select your desired resolution: Why not stay with what you have?

I would only add a dGPU if I would need more power. The UHD630 is enough for everything that is not video editing and gaming.

**Comment by Scope666** [comment]
I agree with Schmocklord, it's a negligible difference.  I also agree with him that you can use the iGPU if you only have one monitor.

I have two and that's why I added the RX 560.

**Comment by Scope666** [comment]
BTW, here's another way to test for Metal support.   (Hackintool)

![image](https://user-images.githubusercontent.com/31927547/84608633-521f0400-ae81-11ea-8500-d2c9b114ceb4.png)

**Comment by jamesfawcett** [comment]
Thanks for this help! Yep I can confirm then no metal support. Some things work great, but I see artifacting in VsCode which is the app I need to use most, so I may end up getting a graphics card after all! There are a few fixes suggested on Reddit that I might give a try first.

The Fenvi T919 is installed and working great straight out of the box. 

I'm just creating another boot install from scratch so it's just purely OpenCore, my current install is infected with some clover bits from the Clover Configurator and other tutorials :) There's a few bits I want to tweak and take out Radeon drivers I don't need. I'm going to attempt those tweaks to the USB ports you suggested above too with Hackintool.

Could I just ask, I can't see this in the OpenCore docs: When I modify the plist, do I then need to run the full reinstall of the OS? Or can I modify the EFI and just boot again?

**Comment by Scope666** [comment]
What I like to do is tweak your EFI on a USB boot stick first, get it to where you're happy, then you can copy / replace the one on your main hard drive.

No need to reinstall the OS, rebooting is enough to see the changes made to the plist.

**Comment by jamesfawcett** [comment]
Thanks to both of you, I've much more understanding now on the setup! It's quite nice knowing the inner workings of your own computer too. I have iGpu displaying in Hackintool now, but it always displays Intel ???.

![image](https://user-images.githubusercontent.com/5245272/85420352-ffbda180-b56a-11ea-9059-8f1b6926f8bd.png)

I've set my device ID using the Base64 convertor in Hackintool from the Hex values of the device (I think) and from the [OpenCore docs](https://dortania.github.io/OpenCore-Desktop-Guide/extras/gpu-patches.html#iGPU-BusID-Patching) .

`<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>PpIAAA==</data>
				<key>device-id</key>
				<data>m8WAhg==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
				<key>model</key>
				<string>Intel UHD Graphics 630 (Desktop)</string>
			</dict>`

Still learning, but I'll update this thread if I get any further.

**Comment by Scope666** [comment]
At the moment mine looks like this:

```
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAAQA==</data>
			</dict>
```

Displays like this:

![image](https://user-images.githubusercontent.com/31927547/85421759-cb35ef80-b542-11ea-96f7-15e161d8d400.png)

**Comment by addisonduda** [comment]
Is there an additional step I am missing and need to take? My iGPU is not showing up. I have the DeviceProperties added, but still cannot see it in Hackintool. I'm using the iMac19,1 plist. Thanks a bunch! 
<img width="640" alt="Screen Shot 2020-06-23 at 12 04 02 PM" src="https://user-images.githubusercontent.com/66935020/85427519-db050200-b549-11ea-81dd-1261c6e1bd3f.png">
<img width="675" alt="Screen Shot 2020-06-23 at 12 04 25 PM" src="https://user-images.githubusercontent.com/66935020/85427528-ddfff280-b549-11ea-9b79-6ecd5aa9e472.png">

**Comment by Scope666** [comment]
Is it enabled in the UEFI (bios) ?   Usually you specifically have to turn it on if you have a dGPU, default will be auto which is disabled.

**Comment by jamesfawcett** [comment]
Mine did that before I enabled it in the BIOS. You have to set it to Enabled and not Automatic. Automatic doesn't show, hope that helps.

**Comment by addisonduda** [comment]
That did the trick. Thanks fellas!!

**Comment by jamesfawcett** [comment]
> At the moment mine looks like this. Perhaps it's your formatting? It looks mangled.
> 
> ```
> <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
> 			<dict>
> 				<key>AAPL,ig-platform-id</key>
> 				<data>BwCbPg==</data>
> 				<key>device-id</key>
> 				<data>mz4AAA==</data>
> 				<key>framebuffer-patch-enable</key>
> 				<data>AQAAAA==</data>
> 				<key>framebuffer-stolenmem</key>
> 				<data>AAAAQA==</data>
> 			</dict>
> ```
> 
> Displays like this:
> 
> ![image](https://user-images.githubusercontent.com/31927547/85421759-cb35ef80-b542-11ea-96f7-15e161d8d400.png)

This for this @Scope666 - with this config mine won't boot past half way. I reverted back, but copied your same platform-id (which seems to be the same as @SchmockLord 's). 

I now have this:

```
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>device-id</key>
				<data>m8WAhg==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
				<key>model</key>
				<string>Intel UHD Graphics 630 (Desktop)</string>
			</dict>
```

My machine boots now, but I still have the ??? next to Intel Generation. 

I must be using the wrong device-id, I'm doing some more research :)

![image](https://user-images.githubusercontent.com/5245272/85434306-c0e51700-b57d-11ea-897a-dd30a15822b0.png)

![image](https://user-images.githubusercontent.com/5245272/85434344-cd696f80-b57d-11ea-89a6-ada4ffd51909.png)

**Comment by jamesfawcett** [comment]
After more researching I've figured it out. When my Intel Generation says ??? it's because I have an invalid iGpu device-id. When I put in a valid one (like yours) then my machine won't boot up. I've enabled verbose boot logging and will be looking for the reasons next :) I am tempted to pull out the 2080 and see if it will boot without it installed.

**Comment by Scope666** [comment]
Take a look here.  I'm using the Device Properties method to "hide" my 2080 Ti from Mac, it works perfectly:

https://dortania.github.io/OpenCore-Desktop-Guide/extras/spoof.html

Also see here under "Comet Lake" for other device-id's to try:

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

**Comment by SchmockLord** [comment]
> Thanks for that! I may look at getting a secondary graphics card, but for now it seems to be working? Mission control and Launchpad works, I can play videos in Quicktime, Are there any other offline tests I can do until my WiFi card arrives? I am going to do a cleaner install, I rushed this one as a "last attempt" before giving up using @SchmockLord 's EFI.
> 
> ![Screenshot 2020-06-14 at 12 01 28](https://user-images.githubusercontent.com/5245272/84600571-1cbeea00-ae72-11ea-924b-28e53e3d679c.png)
> 
> ~Happy to buy a graphics card if I need to. Please tell me if I'm missing something major :)~
> ~I will try the HDMI ports and see the results too.~
> 
> Update - I see the issues. t I have issues with VSCode going glitchy, maybe it relies on using the graphics card, I will take a look at the Radeon RX560 thanks for the heads up :)

@jamesfawcett From your screenshot it appears that you haven't put your own serial numbers in the config.plist yet. You should do that. Just use clover configurator for that and generate yourself a serial number. It is under PlatformInfo-Generic.

**Comment by jamesfawcett** [comment]
> @jamesfawcett From your screenshot it appears that you haven't put your own serial numbers in the config.plist yet. You should do that. Just use clover configurator for that and generate yourself a serial number. It is under PlatformInfo-Generic.

Sorry that was an earlier test, I've reinstalled since then.

Thanks for the tip on disabling my dpu, I used the boot-arg 

I've been on a bit of a journey trying to manually set framebuffers, each time I would get a bit further in the boot up sequence, but at the end of it, it would freeze and the screen would go black. I've finally got HDMI working from my motherboard, the random screen flickering and artifacting has now gone. 

I don't have iGpu working yet, but I think it's progress :)

Here's my device config for the Aurus Z790 for working motherboard HDMI output:

`<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
			<dict>
				<key>device-id</key>
				<data>
				cKEAAA==
				</data>
				<key>layout-id</key>
				<data>
				HAAAAA==
				</data>
			</dict>`

Also @SchmockLord hope you don't mind me tracking my progress here clogging up your repo! I hope these findings might help someone else in the future! :) Let me know if you want me to post updates somewhere else.

![image](https://user-images.githubusercontent.com/5245272/85581803-ce110d00-b634-11ea-8ca8-908e62ea4277.png)

**Comment by jamesfawcett** [comment]
I think I celebrated too early, my motherboard HDMI port works when I don't try change the device config for the PciRoot(0x0)/Pci(0x2,0x0). I am struggling to debug it because the verbose logging goes off screen and there's no visual output after it boots.

**Comment by Scope666** [comment]
That seems like a victory to me, I've NEVER gotten anything out of the motherboard's HDMI port, only the DP.

**Comment by jamesfawcett** [comment]
Thanks :) I've experimented with the WhateverGreen boot flags too and also disabled shikigva=80 but it did the same. I have enabled WhateverGreen logging with `-wegdbg` but not sure yet where that logs to, but I'll try investigate. I'm getting faster now at booting up Windows to fix the config.plist each time 😂

**Comment by jamesfawcett** [comment]
Just to update this thread, I've given up on trying to get iGpu working, I think I'm also going to put it down to these processors being too new and not supported.

I've ordered the MSI variant of the 710 Nvidia cards mentioned before. The 2gb version was just over £40 and will enable metal support natively:
https://www.scan.co.uk/products/2gb-msi-geforce-gt-710-passive-single-slot-pcie-20-(x16)-1800mhz-ddr3-gpu-954mhz-cores-192-hdmi-dvi-

Here's someone on reddit with the same graphics card and device properties: https://www.reddit.com/r/hackintosh/comments/f6s2bt/succes_guide_hackpro_catalina_i7_9700_asrock/
```
PciRoot(0x0)/Pci(0x2,0x0):

AAPL,ig-platform-id: 0300923E

framebuffer-patch-enable: 01000000

framebuffer-stolenmem: 00003001
```

I'm going to install it in the very bottom slot so it doesn't affect the performance of my 2080ti when I boot into Windows. I'm also going to remove the boot flag for disabling all DGPUs and use @Scope666 's method here to disable the 2080i:

```
Take a look here. I'm using the Device Properties method to "hide" my 2080 Ti from Mac, it works perfectly:

https://dortania.github.io/OpenCore-Desktop-Guide/extras/spoof.html
```

If anyone's interested, it was this comparison of my entry-level 2018 Macbook pro compared to my Hackintosh that made me decide I need a graphics card working. Also, having iGPU set to Enabled instead of Auto in bios meant I permanently had a second desktop in Windows, even with the device disabled in device properties. I always have the displayport and HDMI connected to my monitor and didn't want to have to keep removing it. 

Here's the results, the Mac Pro outperforms the PC quite a bit with metal support:

Hackintosh:
![screencapture-browser-geekbench-v5-cpu-2670446-2020-06-24-18_18_00](https://user-images.githubusercontent.com/5245272/86010313-2704ea80-ba13-11ea-8bc8-664145167ce9.png)

Entry level macbook pro:
![screencapture-browser-geekbench-v5-cpu-2670600-2020-06-24-18_35_51](https://user-images.githubusercontent.com/5245272/86010373-371cca00-ba13-11ea-8fce-210b3e187d4d.png)


It will be interesting to see how the Hackintosh performs with the MSI 710 installed tomorrow.

**Comment by jamesfawcett** [comment]
Fitted the MSI 710 and added it to my plist. It booted straight up, full metal support confirmed in Hackintool!

The difference in speed is night and day, it's fantastic. Without the GPU, when changing windows or performing small computing tasks, the cpu fans would rev up every time (which was quite annoying!). Now, everything is silent, and the 710 looks quite snug and tidy in the bottom slot:

![image](https://user-images.githubusercontent.com/5245272/86153935-488cd180-bafa-11ea-9a20-b8a38bbeb7f4.png)

My next mission is to get the headphone socket on the front panel working. Thanks for your guide on how to do the USB ports, those are all sorted now. Interesting to find out the differences between Type C and Type C + SW USB ports depending on if they are reversible. I had two separate Type C for each way round.

Here's my results now with the MSI 710 installed, it doesn't seem much in comparison to below, but it feels much faster!

![screencapture-browser-geekbench-v5-cpu-2749619-2020-06-30-15_29_12 - with 710](https://user-images.githubusercontent.com/5245272/86154260-b89b5780-bafa-11ea-84d3-7c04397f00bc.png)

**Comment by SimeJah** [comment]
Wait so sorry if I am wrong.. but I thought running RTX cards om hackintosh was impossible. Did you manage to get a 2080Ti to work on a hackintosh!? :D

**Comment by jamesfawcett** [comment]
Hello I have video output from it but no metal support, I don't believe my iGpu is working yet either but I use the machine every day. I bought a cheap Nvidia 710 silent DGpu and now metal support works great and the machine is fast, I have the 2080ti disabled in my config.plist

**Comment by mariopeixoto** [comment]
@jamesfawcett Hi! Which method did you use to disable the 2080ti? Did you use the DeviceProperties method from https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html ?

**Comment by jamesfawcett** [comment]
Hi @mariopeixoto here's my full deviceproperties:

`<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>name</key>
				<data>I2Rpc3BsYXk=</data>
				<key>IOName</key>
				<string>#display</string>
				<key>class-code</key>
				<data>/////w==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x14,0x0)</key>
			<dict>
				<key>acpi-wake-type</key>
				<data>AQ==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>device-id</key>
				<data>kj4AAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>model</key>
				<string>Intel UHD Graphics 630 (Desktop)</string>
			</dict>
			<key>PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0, 0x0)</key>
			<dict>
				<key>device-id</key>
				<data>8hUAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>device-id</key>
				<data>cKEAAA==</data>
				<key>layout-id</key>
				<data>BwAAAA==</data>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>`

The bit you are looking for is:

`<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>name</key>
				<data>I2Rpc3BsYXk=</data>
				<key>IOName</key>
				<string>#display</string>
				<key>class-code</key>
				<data>/////w==</data>
			</dict>`


Thanks
James

**Comment by Boy447374** [comment]
> Hello I have video output from it but no metal support, I don't believe my iGpu is working yet either but I use the machine every day. I bought a cheap Nvidia 710 silent DGpu and now metal support works great and the machine is fast, I have the 2080ti disabled in my config.plist

How do you feel about sharing your EFI? Which config file out of the three did you use? I have a 2080ti and not having any luck booting.

**Comment by jamesfawcett** [comment]
Happy to share! I'll push my latest config tomorrow and add a link here. How far are you getting with booting? Just no video out?

I have a rx560/580 (can't remember!) card now because the NVidia710 wouldn't support my 48" widescreen 5220x3400px but it was a great cars, shame if couldn't do the higher resolution even with switchresx.

I'll post a link tomorrow for you

**Comment by jamesfawcett** [comment]
Hi @Boy447374 

I was still using OpenCore 0.6.6. This repo is currently on 0.6.9 so I decided to update. I also couldn't get mine to boot. 

After going through line by line, it was this change stopping my system booting:

```
<key>AppleXcpmCfgLock</key>
<false/>
```

At some point, this has changed from true > false. I'm not sure why @SchmockLord might be able to tell us?

My 2080ti is disabled with:

```
<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>name</key>
				<data>I2Rpc3BsYXk=</data>
				<key>IOName</key>
				<string>#display</string>
				<key>class-code</key>
				<data>/////w==</data>
			</dict>
```

![image](https://user-images.githubusercontent.com/5245272/120907145-1ca59480-c657-11eb-84ad-2ee83a12aa97.png)

If I enable it, it does do Video out, but without metal support. 

I highly recommend the RX560 it's a good card, quite compact and small.

![image](https://user-images.githubusercontent.com/5245272/120907174-4fe82380-c657-11eb-9cd4-d4a420789b3f.png)

I'll invite you to my private repo so you can see my full EFI if you want to?

Thanks
James
