### ISSUE TITLE
USB Issues

### ISSUE THREAD

**Issue by crashmaster4000** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#175]
Hello everyone! I hate asking this because I feel I'm missing something obvious but here goes. I'm running Big Sur 11.4 on a Z490 Vision D with BIOS version 6, 32GB RAM and a Radeon RX 5700 XT, and am having USB issues. When I was running OC 0.7.0 everything USB-wise was working perfectly, but after the update to 0.7.1 my USB 3 devices are not showing up after booting. I have flash drives with old versions of OpenCore on them going back many months and when I test the 0.7.0 flash drive everything works, but with the 0.7.1 flash drive I don't see USD 3 devices (USB 2 and the front USB-C works perfectly.) I redownloaded the 0.7.1 archive & created a new flash drive and still the same problem. Does anyone have any suggestions please?

Thanks!
Crash

**Comment by AlaKru** [comment]
I am having same issue. No usb 3 ports available, was having issues with hubs prior to 7.0 being stubborn and having to separate low and high speed devices for them all to work. As soon as I got it fixed, updated...all usb 3 not working.

**Comment by AlaKru** [comment]
Apparently it's only the 4 port usb 3 internal hub not working. Doesn't even show up in hackintool.

**Comment by SchmockLord** [comment]
Which SMBIOS are you guys using?

**Comment by crashmaster4000** [comment]
Morning.  I'm using iMac20,2. Thanks for responding!

**Comment by AlaKru** [comment]
Hey, thanks. Running 20,2. I tried port mapping(w/ hackintool) without using injectall first. Still only one usb 3 port visible now above thunderbolt port, but it for some reason doesn’t have consistent connection. Devices keep switching on and off. 2.1 bus on 4 ports visible.

**Comment by SchmockLord** [comment]
Can you please test this one?

In this I have gone back to my old method, USBInjectAll.kext + SSDT-UIAC-USB-Z490-VISIOND-ALTERNATIVE-3.aml.

It seems a lot of people have issues since I introduced the Kext-only version from USBPortMapping.command. 

The base is the current release with OC 0.7.1 but with the newest USBInjectAll v0.7.7.

[EFI.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/6871167/EFI.zip)

**Comment by crashmaster4000** [comment]
I can test that this evening - I’ll let you know the results ASAP. Thank you.

**Comment by crashmaster4000** [comment]
OK just created a new flash drive with your modified EFI folder and the only working USB3 port is the leftmost red port. USB 2 drives are recognized in all ports. Let me know what I can do to help.

**Comment by AlaKru** [comment]
> OK just created a new flash drive with your modified EFI folder and the only working USB3 port is the leftmost red port. USB 2 drives are recognized in all ports. Let me know what I can do to help.

That’s the same usb 3 port I had working after port mapping. I will give new USBinjectall a try when I have time.

**Comment by AlaKru** [comment]
Still sees USB 3 devices as 2.1. And then I lose other devices that are actually on a usb 2 hub plugged into usb 2 port only.

**Comment by AlaKru** [comment]
Random restarts are back, but that’s due to it changing audio sample rates on apollo(thunferbolt/apple usb) when usb gets confused. But ss04 and hs07 still not showing up in hackintool. Only usb 3 still ss03 but does not keep a constant connection when device is plugged in.

**Comment by crashmaster4000** [comment]
Sounds like we are having about the same luck. I’m going to play with it a bit more tonight and see if I can find anything that looks off.

**Comment by SchmockLord** [comment]
I think I have found the issue. Set Xhci Port limit to 1. it is in the kernel quirks section.

**Comment by crashmaster4000** [comment]
Currently buying cat food - will test that as soon as I get home and feed the gang. Woo!!!!

**Comment by crashmaster4000** [comment]
Ok changed the value from Boolean to number and added a value of 1. Rebooted, reset NVRAM and still no usb 3 ports.

**Comment by crashmaster4000** [comment]
Ok it seems to be working!

last question - I used your plist iGPU computing only - can you please post that with the modifications? Or what do I need to do to that plist to make it work?

Thanks!!!

PS - after this I’ll kick a few bucks to your patreon page

**Comment by AlaKru** [comment]
Set Xhci Port limit to 1 seems to work, usb 3 showing now. But with USBinjectall/usb 3 working, some of my bigger usb devices not showing up until reconnect them on my external usb 2 hub. Do you think I should use Hackintool to create a port map now that I can see all ports working?
Thanks Chris and Crashmaster4000 for the help.

**Comment by crashmaster4000** [comment]
Hey don’t thank me- it’s all his work! I’m just along for the ride…

I’ll go try out a large-capacity drive - I’ve got some 2TB flash and spinning metal drives I can experiment with.

**Comment by AlaKru** [comment]
Sounds good. Everytime I plug a device into a port I lose something else. I thought this was what I had just fixed right before the update. Can’t remember the combination that worked, but the 2 USB ports above usb c ports seem mostly useless.

**Comment by AlaKru** [comment]
I should prob let you know that I have an apple display on thunderbolt which registers as applebus and takes up about 6 of my ports in hackintool.

**Comment by crashmaster4000** [comment]
Ok just plugged in usb 3 flash drives, a WD 4TB external hard drive and a usb-c case with an M.2 NVME drive inside it and they all worked as expected. Even plugged in the NVME drive into the rear Thunderbolt/USB-C port and it worked.

Other than getting the instructions on how to modify the old plist for using the iGPU for computation only I’d call it fixed here.

**Comment by AlaKru** [comment]
Devices now showing up. But usbinjectall has caused is to run sluggish again, kernel panics, and long shutdown. Glad it works for you though. I will try to port map again when I get back in town. Thanks again.

**Comment by SchmockLord** [comment]
> Sounds good. Everytime I plug a device into a port I lose something else. I thought this was what I had just fixed right before the update. Can’t remember the combination that worked, but the 2 USB ports above usb c ports seem mostly useless.

The behavior you describe can be caused by exceeding the 15 port limit. But also check if your CSM and Legacy USB are disabled.
