### ISSUE TITLE
v5.2 USB Issues

### ISSUE THREAD

**Issue by MidnightDiner** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#176]
Hey there,

First off, thank you for all your consistent releases! 

I recently updated to your latest v5.2 with the fixes for USB that's been changed back to USBInjectAll. I'm still encountering issues with my USB ports when compared to older OC0.6.8 releases. 

**USB issue description:**
- Currently my 'BIOS' USB port works (when it shouldn't. I don't keep anything plugged in there though)
- The two red USB 3.2 ports next to the thunderbolt ports don't work and do not provide power either. 
- All other ports work as expected. 
- I do have one thunderbolt 3 device connected..if that changes anything. 
- I've tried changing the USB legacy support options in BIOS, but that didn't change anything. 

**System specs:**
Gigabyte Vision D Z490 Motherboard
using 'config_iMac20,2_iGPU_computing_only.plist'
Intel i7 8-core (10700k)
Radeon 5700XT
32GB Ram

Any help would be greatly appreciated. Thanks!

**Comment by SchmockLord** [comment]
Hey, 

can you please try this one? I have added XHCI-unsupported.kext. Maybe this will help with the issues. Otherwise, I can only guess that these issues come from the 15 port limit, which my configuration exceeds. 

[EFI_experimental.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/6911343/EFI_experimental.zip)

**Comment by MidnightDiner** [comment]
I gave it a try. It didn't seem to change anything. Noticed this in the boot sequence. image attached. 
![IMG_4565](https://user-images.githubusercontent.com/66181565/127745130-a120f218-0895-42a4-83e5-ef7fc673dc77.jpeg)

**Comment by SchmockLord** [comment]
Ok. Then try this one. Here I tried to stay within the 15 port limit again.

But without this xhci-unsupported.kext

[EFI_v5.3_ReleaseCandidate#2.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/6911470/EFI_v5.3_ReleaseCandidate.2.zip)

**Comment by MidnightDiner** [comment]
'EFI_v5.3_ReleaseCandidate.2.zip' caused all USB ports to stop working, no power delivery either. I've reverted back to 5.2 for now. 

Just want to say thanks for trying to fix this. I'm open to trying any new options you might have.

**Comment by SchmockLord** [comment]
Here is another one. Changed the SSDT-UIAC.aml, disabled the XHCI-PortLimit Quirk in the config.

[EFI_v5.3_ReleaseCandidate#3.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/6913269/EFI_v5.3_ReleaseCandidate.3.zip)

**Comment by MidnightDiner** [comment]
This is the one! :) All USB ports working except for the BIOS USB port. So far I haven't had any issues. I'll definitely let you know if anything happens. Very thankful you took the time to resolve this!

**Comment by SchmockLord** [comment]
Thanks for helping me out with testing! I sold this board long ago. So I am doing this blind.

Check again with the current release. But I think everything is fine now.
