### ISSUE TITLE
15 port limit- w/ apple USB

### ISSUE THREAD

**Issue by AlaKru** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#177]
Just creating a new issue to keep from scattering this issue in multiple places. I have not tried your new USB configuration yet as I am using HS12, but I will try shortly, I took a snapshot using the config that you asked us to try with xhci portlimit set to 1 and USBinjectall. All devices show, but kernal panics(crashes) and boot/shutdown slow. Do you think my thunderbolt display could be the issue? It uses ports labled appleUSB, but I am not over the 15 port limit in Hackintool. I have a USB 3 hub plugged into SS07 and a USB 2 hub's plugged into HS09 and HS10. Thunderbolt daisy chain->UAD satellite->Apollo twin->Apple Thunderbolt Display. 
![Screen Shot 2021-08-02 at 5 39 54 PM](https://user-images.githubusercontent.com/71417904/127927298-8cbbbada-ccd7-495b-bbc0-1535266a867d.png)

![Screen Shot 2021-08-02 at 2 28 36 PM](https://user-images.githubusercontent.com/71417904/127907228-20c7e698-6c39-4948-892c-90b83c5b7a39.png)

**Comment by SchmockLord** [comment]
I think there is a misunderstanding how the 15 ports are counted. Not only the green and used ones are counted, all HSxx and SSxx ports that you can see in Hackintool are counted. But I think not the ones that are behind the thunderbolt dock for example. Only the ones that are on your motherboard. And the configs I asked you to test were not working properly.

**Comment by AlaKru** [comment]
Yes, I had just realized I was understanding it wrong after looking at your directions closer. I have been trying different configurations and I think I finally found one that will work. I could not remove some USB ports from display, so I had to remove more from rear and front MB panel. Thank you for your help and time. I will send something your way soon, you have earned it.
