### ISSUE TITLE
Summary before ordering the same hardware

### ISSUE THREAD

**Issue by obarlev** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#18]
Hi Chris,
Thanks for this awesome repo and all the updates.
Ordering my own machine parts these days - only need to choose CPU + board. 
Planning to purchase same CPU and motherboard like your build - after a few weeks, can you summarise? 
How stable your machine? Need it mostly for software development.
The stability is a critical factor for me (less care about graphic performance or benchmark numbers - want a strong and stable machine for the following few years)
Thanks again for your great work here!

**Comment by SchmockLord** [comment]
Thank you very much. It is super stable and I would buy the same CPU+MoBo again. The only issues I had were Sleep/Wake Issues. But I fixed that. The main reason was, that the CNVi of the onboard Intel Wifi 6 was waking it up. No stability issues.
