### ISSUE TITLE
New release 0.7.3 Catalina not boot (Solved)

### ISSUE THREAD

**Issue by MirkoMela** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#182]
Hello, thanks for update to new 0.7.3 but this release not show or detect Macintosh HD system disk at boot , but only Reset Pram or other disk like Usb installer etc . I have revert to 0.7.2 no issues .

**Comment by SchmockLord** [comment]
Change csr-active-config to E7030000. Then you should see all drives again.

I did switch to 00000000 to use Secure Boot.

**Comment by MirkoMela** [comment]
Thanks for reply. The csr-active-config is already set to E7030000. I also tried to change the type of security but the same problem. 🥲

**Comment by MirkoMela** [comment]
I solved by changing the values of APFS MinDate e MinVersion to -1
