### ISSUE TITLE
Is there anyone using Mac Big Sur version 11.3+ working with USB 2.0? 

### ISSUE THREAD

**Issue by trinhvanminh2009** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#183]
I've been using Mac Big Sur 11.0.1 for a few months. All of my USB ports are working well.  I just updated to mac 11.5.2 and all USB 2.0 ports are not working anymore.

**Comment by Ptitlion** [comment]
The usb ports have been working very poorly since the last maps. Now I'm on BigSur 11.6 and all ports are working fine. But for that I made my own Usbmap.kext and removed usbinjectall.

**Comment by SchmockLord** [comment]
@Ptitlion Can you please share your Usbmap.kext?

I might add it to the repo.

**Comment by formeinyourmind** [comment]
> @Ptitlion Can you please share your Usbmap.kext?
> 
> 
> 
> I might add it to the repo. 

Tell people install hackintool, they can export their usbmap.kext from that app because mainboards are different

**Comment by Ptitlion** [comment]
> @Ptitlion Can you please share your Usbmap.kext?
> 
> I might add it to the repo.

Hi ! Of course, nothing crazy but here is the file. I'm not used to GitHub, hope it's the right way.

This is my UsbMap for my Z490 Vision D Rev 1.1
All USB2 and USB3 type A ports work for me.

This is the same configuration as your "USB-port-Configuration-Alternative-1.png" image except HS10 enabled and HS01 disabled.

I haven't tested USB C yet, I don't need it at the moment.

Xhciportlimit to false, removed USBinjectAll and replaced with USBMap.kext

[USBMap_15.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/7165436/USBMap_15.zip)

**Comment by SchmockLord** [comment]
@Ptitlion Thanks for providing. I have checked it and it looks very good. I duplicated it and made a version for iMac20,2 and iMacPro1,1.

It is now included in the current release.
