### ISSUE TITLE
config.plist Error

### ISSUE THREAD

**Issue by Ptitlion** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#186]
Hi @SchmockLord, I noticed potential errors in your config.plist 0.7.3 and 0.7.3 + USB

CustomKernel Boolean FALSE is missing in Scheme

Remove space from Ethernet path PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0, 0x0), it should be PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0)

Remove commas in the titles of USB Map.kext because it is prohibited

I also modified 2 .aml, maybe that can be useful.

Regards

[ModifAML.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/7308077/ModifAML.zip)

**Comment by AlaKru** [comment]
No disrespect meant, but you seem to know what you're talking about and I am still learning. Can anyone else confirm this? What exactly does this fix?
