### ISSUE TITLE
OC 0.7.4 - ACPI Question

### ISSUE THREAD

**Issue by gtrooper** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#188]
Can anyone explain why while in the ACPI Folder there are 7 .aml files, in the config.plist - ACPI - ADD, Only 5 of them are added ? I had the impression ALL 7 are needed.

**Comment by SchmockLord** [comment]
Thanks for this hint. This way I found out that SSDT-EC-USBX.aml was not in the config.plist which might have caused the USB-issues people had. Just fixed that.
