### ISSUE TITLE
Update to OC 0.7.6 causes Hackintosh to reboot at start of Finder Desktop

### ISSUE THREAD

**Issue by crashmaster4000** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#194]
After creating a new USB flash boot drive then attempting to boot 0.7.6 after running .0.7.5 successfully, everything works as expected until the Desktop tries to load - upon which the pc will reboot itself after a few seconds. I've created three different flash drives and re-downloaded your EFI folder three times but still have the same result. I'm running BigSur 11.6.1 on a Core i9-10900K w/32GB ram, one NVME boot drive (APFS format), one 10TB hard drive (HFS format) and a second SSD which is connected thru the SATA port (also APFS.) I'm using an RX-5600XT for video output.

Here's the panic report:
panic(cpu 4 caller 0xffffff801ac4bc97): "jhash_getvnode: bad devt on object.\n"@/System/Volumes/Data/SWE/macOS/BuildRoots/220e8a1b79/Library/Caches/com.apple.xbs/Sources/apfs/apfs-1677.141.2/kext/apfs_vfsutils.c:222
Backtrace (CPU 4), Frame : Return Address
0xffffffc1259ab480 : 0xffffff8017a8d25d mach_kernel : _handle_debugger_trap + 0x3fd
0xffffffc1259ab4d0 : 0xffffff8017bd49d3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffc1259ab510 : 0xffffff8017bc4fca mach_kernel : _kernel_trap + 0x55a
0xffffffc1259ab560 : 0xffffff8017a31a2f mach_kernel : _return_from_trap + 0xff
0xffffffc1259ab580 : 0xffffff8017a8ca7d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffc1259ab6a0 : 0xffffff8017a8cd73 mach_kernel : _panic_trap_to_debugger + 0x273
0xffffffc1259ab710 : 0xffffff801829d8fa mach_kernel : _panic + 0x54
0xffffffc1259ab780 : 0xffffff801ac4bc97 com.apple.filesystems.apfs : _apfs_jhash_insertvnode
0xffffffc1259ab7d0 : 0xffffff801ac4b9d1 com.apple.filesystems.apfs : _apfs_jhash_getvnode_internal + 0x78
0xffffffc1259ab830 : 0xffffff801ac4d2ae com.apple.filesystems.apfs : __get_inode_with_lookaside_and_hint + 0x30
0xffffffc1259ab870 : 0xffffff801ac07607 com.apple.filesystems.apfs : _attrlistbulk_iterator + 0x1e1
0xffffffc1259ab940 : 0xffffff801ac4dac7 com.apple.filesystems.apfs : _iterate_raw_jobjs_with_hint + 0x21f
0xffffffc1259ab9f0 : 0xffffff801ac03630 com.apple.filesystems.apfs : _apfs_vnop_getattrlistbulk + 0x2d8
0xffffffc1259abdf0 : 0xffffff8017cf7a28 mach_kernel : _getattrlistbulk + 0x608
0xffffffc1259abf40 : 0xffffff801813fd2e mach_kernel : _unix_syscall64 + 0x2ce
0xffffffc1259abfa0 : 0xffffff8017a321f6 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.filesystems.apfs(1677.141.2)[A2E36135-081F-3EE7-9F8A-53103C506BE8]@0xffffff801abab000->0xffffff801ad1afff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[511FC3DC-D63F-3993-9C5C-613AF51D837C]@0xffffff8018efe000->0xffffff8018f07fff
            dependency: com.apple.driver.AppleEffaceableStorage(1.0)[7AC5E118-B326-3E46-980F-4706B9C5ABF0]@0xffffff8018f11000->0xffffff8018f16fff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[3040B1E0-7488-35C7-9DB9-ED6C9EF965E7]@0xffffff801936d000->0xffffff8019373fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[AEB16297-5950-3E23-84C4-2E9928878BA1]@0xffffff801a66e000->0xffffff801a67ffff
            dependency: com.apple.kec.corecrypto(11.1)[379F0025-A70B-3A5D-A92F-3C557D6E4E68]@0xffffff801ad48000->0xffffff801add9fff
            dependency: com.apple.security.AppleImage4(3.0.0)[7B75FFFD-E85A-3686-8D37-27B84E4DFE6D]@0xffffff8018f7d000->0xffffff8018f8dfff

Process name corresponding to current thread: SystemUIServer
Boot args: agdpmod=pikera shikigva=80 -lilubetaall keepsyms=1 

Mac OS version:
20G224

Kernel version:
Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64
Kernel UUID: ABC69550-60C2-34FE-B307-C24A8C39309C
KernelCache slide: 0x0000000017800000
KernelCache base:  0xffffff8017a00000
Kernel slide:      0x0000000017810000
Kernel text base:  0xffffff8017a10000
__HIB  text base: 0xffffff8017900000
System model name: iMac20,2 (Mac-AF89B6D9451A490B)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 17938864819
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000042d3d5cca
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000017cf16bbba 0x0000000000000000

Any suggestions would be appreciated! And thank you again for sharing your knowledge with the community.

**Comment by SchmockLord** [comment]
Can you try to use this Kext?

I have noticed that I accidentally updated the IntelMausiEthernet.kext but the old one had 284kb and the new one 422kb although they have the same version number.
[IntelMausiEthernet.kext.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/7788130/IntelMausiEthernet.kext.zip)

**Comment by crashmaster4000** [comment]
Thanks - I’ll give it a try this evening and let you know the results. Appreciate your time!

**Comment by crashmaster4000** [comment]
Evening!  I just created a new flash drive with the other version of the ethernet kext and it still crashes at the desktop. I also tried downloading all of the kexts (current release and also the previous release version) found in your zip archive and the same thing happens - desktop starts to load then reboot. 

Is there a specific version of the Gigabyte BIOS I should be using? I am still on F6 - should I update it to F20?

Thanks for your assistance,
crash

**Comment by mueex** [comment]
I'm also using Big Sur 11.6 and can't complain about any issues after updating to OC 0.7.6 (from 0.7.4). Everything works with the files originally uploaded by Chris on December 23. Can anyone else please confirm the problem described by cashmaster4000?

**Comment by crashmaster4000** [comment]
OK good news / bad news. Good news - I figured out what the problem is. I have a 10GB switch and am using the red 2.5GB port to connect to the network. As soon as I switched to the 1GB port the computer boots! Yay!  So, what do I need to modify to get that port working?

Also, I was using the plist based off of "config_iMac20,2_iGPU_computing_only.plist" and in the Kernel->add-> Item 4 section you have "USBMap_iMacPro11.kext" when I think it should be "USBMap_iMac202.kext" (USB ports were not working until I changed that)

Please let me know if you have any suggestions about the 2.5GB port.

Thanks!
Crash

**Comment by okkina** [comment]
2.5GB port. Crashes when used. me too

**Comment by imsuperimposed** [comment]
I've had that since 0.7.2 just resided to 1gbe in the end

**Comment by okkina** [comment]
Up to 0.7.5, 2.5GB port could be used

**Comment by crashmaster4000** [comment]
okkina - same here. Worked fine in 0.7.5 but not in 0.7.6. I have a friend with the same setup as mine and he is on 0.7.6 and has no issues with the 2.5GB port. He is using a different EFI folder - not sure if he created it or got it from somewhere on the internet. I'll ask him today & post here.

**Comment by crashmaster4000** [comment]
I just received a copy of his EFI folder, changed the serial numbers, etc. and using his 0.7.6, my Mac running BigSur 11.6.1 booted perfectly and the 2.5GB port worked without crashing. He downloaded it from another site - do you want me to upload the EFI folder here? Thanks!

**Comment by okkina** [comment]
Please by all means
that's strange

**Comment by crashmaster4000** [comment]
@SchmockLord - do I have your permission to upload his EFI folder here? I just found out where it came from - another hackintosh web site that's been the source of some controversy over the years - and I don't want to cause any issues. Please let me know here or at crashmaster4000@gmail.com

Thanks and Happy New Year!

**Comment by mueex** [comment]
I would also be interested in that. For comparison purposes alone.

**Comment by ashishpandey** [comment]
I was having a similar crash:
* will boot fine till the login screen
* will reboot as soon as I login (so consistent with this issue, when desktop is opened)

I suspect this may be due to the changed PCI key for 2.5G Ethernet. I reverted it back to `0x1C,0x1` which is also what I see from Hacintool PCIe tab 
my change is [here](https://github.com/ashishpandey/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/commit/fe656faf3b951bbbd3b321f9e8c883762f2460e2). I also pointed to correct USB config for iMac20,2

No crashes since the above fix

**Comment by SchmockLord** [comment]
Can you all try the current release?

It should be fixed now.

I messed up the USB-Map kext in the iMac20,2 configs and mistakenly changed the PCI-Path to the i225-V.

This caused this crash at Startup.

**Comment by crashmaster4000** [comment]
Hey thanks for the reupload - testing now and everything seems to be working as expected.
