### ISSUE TITLE
iMac 20,2 plists using USBMap_iMacPro11.kext breaks USB

### ISSUE THREAD

**Issue by Zjcc56** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#196]
the two imac 20,2 configs are using USBMap_iMacPro11.kext break most of my usb ports when i switch to the USBMap_iMac202.kext all is well

**Comment by ashishpandey** [comment]
I believe this was fixed as of https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/commit/5cbded4671f3aa3cd34ebd4d03b1fa33e93e23de

**Comment by SchmockLord** [comment]
Yes, this issue should be fixed.
