### ISSUE TITLE
Booting, Thunderbolt issues after 7.6 Reupload

### ISSUE THREAD

**Issue by AlaKru** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#198]
Boot up hangs, and now thunderbolt screen flickers. The previous version was flawless. I now have this on my screen which I have never had on any Mac. What happened
![Screen Shot 2022-01-03 at 1 52 57 PM](https://user-images.githubusercontent.com/71417904/147968698-9b80304b-53a0-4133-8a72-81631fb6e9c1.png)
?

**Comment by SchmockLord** [comment]
Just enable the 2 Thunderbolt SSDTs. I have disabled them. Will enable them again with the next release.

**Comment by AlaKru** [comment]
Thanks. Yeah, I just saw that and got it working. What is the reason they are disabled? I also realized that the filename for SSDT-DTPG.aml has changed from what it used to be which was SSDT-DTGP.aml (which I created and have been using since my original build per your readme instructions) in your previous versions which may have been causing me/us some issues as well.
