### ISSUE TITLE
Gigabyte Vision D or Asus ROG Strix Z490-E Gaming?

### ISSUE THREAD

**Issue by henryxrl** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#20]
Hi,

I'm looking to get a similar build. The only struggling is the choice of mother board between Gigabyte Vision D and Asus ROG Strix Z490-E Gaming... They have about the same price tag and it seems they're both good for Hackintosh. I know you're using Vision D but would you recommend one board over another? Is one more stable and better in terms of overclockability than another?

FYI, the reason I ask this was because I have never used a Gigabyte board before, nor can I find sufficient information on this particular motherboard. Any input is appreciated. Thanks!

Best,
Henry

**Comment by SchmockLord** [comment]
_Is one more stable and better in terms of overclockability than another?_
I don't think so. I am happy with the Vision D. 

If you want the easy way, just buy the Vision D and copy my config.
