### ISSUE TITLE
v9 still has OpenCore v0.7.6

### ISSUE THREAD

**Issue by ethankhoa** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#200]
Upgraded to v9 (OC 0.7.7) and kept getting OCS errors on boot and noticed that the OpenCore version is still 0.7.6 in the release files.

My errors went away when I updated to the current version.

**Comment by g3d** [comment]
Same problem, 0.7.6 and boot warnings

**Comment by SchmockLord** [comment]
Guys, you were right. Somehow the OpenCore.efi wasn't updated to 0.7.7. Did just correct that. Thanks!
