### ISSUE TITLE
Help, lost the original Thunderbolt chip firmware.

### ISSUE THREAD

**Issue by rainyx** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#202]
I'm using Z490 Vision D with custom Thunderbolt chip firmware on my hackintosh, and everything is ok. Recently, I want to restore my Thunderbolt chip firmware, but i lost the original firmware file, can anybody send me a copy, thank you so much. T_T

**Comment by g3d** [comment]
I didn't flash custom firmware, so I can dump it for you if needed. Do you have instructions how to do it?

**Comment by rainyx** [comment]
> UPD: I've checked instructions and it seems I need additional hardware, so I would not be able to do it

It's okay, thank you.

**Comment by rainyx** [comment]
> @rainyx I checked my Cloud Drive and fortunately I keep Backups of the original flashes on the cloud. You should do that too ;) [original_tb3_firmware_Z490_Vision-D.bin.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/8047628/original_tb3_firmware_Z490_Vision-D.bin.zip)

Thank you, your are the best!😀
