### ISSUE TITLE
stuck on startup

### ISSUE THREAD

**Issue by wytheglobal** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#206]
HI, I followed the documentation, successfully see "EFI", "Install Big Sur" interface, and i click Install Big Sur, after waiting apple logo and indicator bar loaded for a while, the screen stopped with black background, only shows  "support/mac/startup".

my OC debug log is bellow: can any one help?
[opencore-2022-02-17-192311.txt](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/8091656/opencore-2022-02-17-192311.txt)

**Comment by SchmockLord** [comment]
What hardware do you have?

GPU? iGPU? Which SMBIOS?

Can you press two keys to see if that wakes the display?

And please plugin a headset and check if you can hear a sound.

**Comment by wytheglobal** [comment]
Thank you for you kindly help, my hardware is :
CPU：i9-10900F (no gpu inside cpu)
Motherboard: Gigabyte Z490 AORUS PRO AX
GPU: Radeon RX 590 Graphics
Wifi/BT: MQUPIN fenvi T919 Wireless Card with BCM94360CD
SMBIOS: config_iMacPro1,1_requires AMD GPU.plist

actually the screen is not totally black
![image](https://user-images.githubusercontent.com/91439960/154709362-26b7824d-6add-41e4-bcd4-355a402cc4d5.png)
![image](https://user-images.githubusercontent.com/91439960/154709397-148deb75-386f-4820-8078-71f451a89e25.png)

**Comment by SchmockLord** [comment]
First of all: you have a different Board. 

Try disabling SSDT-DTGP.aml and SSDT-TB3HP.aml, cause your board doesn't have Thunderbolt.

And try setting Kernel-Quirks-XHCIPortlimit although I don't think this is the reason, because the USB Mapping the the SSDT-USB-Ports-Z490-VisionD.aml isn't for this board, but reduced to 15 ports already.

Then throw out all bootargs except these: agdpmod=pikera keepsyms=1

After that you can also try to leave out agdpmod=pikera.

**Comment by wytheglobal** [comment]
Man, you are a genius, I did what you told me, and it works great, I can enter into the installation. 

In the meantime, I have tried to work out a minimal working EFI following this manual: https://dortania.github.io/OpenCore-Install-Guide/ktext.html 
I'm able to enter the install process, but seems can't figure out my USB keyboard, do you know what's going on?
![image](https://user-images.githubusercontent.com/91439960/154735571-f25f69df-85f8-4bad-8363-cb286a4becb6.png)

my EFI 
[EFI.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/8099318/EFI.zip)

error log: 
[opencore-2022-02-18-174234.txt](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/8099323/opencore-2022-02-18-174234.txt)

something i think may be strange:
![image](https://user-images.githubusercontent.com/91439960/154735885-86ad2640-0420-4f6b-a12a-d3cf408f0299.png)

If I set Kernel-Quirks-XHCIPortlimit to false, this EFI will not work anymore, it will stuck in AppleUSBHostPort fail and after a while, shows "support/mac/startup"
I'm very curious at what's going on

**Comment by SchmockLord** [comment]
Try XhciPortLimit and try all USB ports until you find one where Keyboard works. After the installation you have to do a proper USB port config for your board. 

Von meinem iPhone gesendet

**Comment by wytheglobal** [comment]
Thanks a lot, I will have a try.
