### ISSUE TITLE
Stuck on Apple logo 

### ISSUE THREAD

**Issue by ArmaniKida** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#21]
When I use your EFI on boot it stays on the apple logo with a full bar and no power to mouse or keyboard.

**Comment by addisonduda** [comment]
Are you connected to the internet? The install requires this. I needed an Ethernet connection for mine to work, especially because I’m in an apartment with loads of other connections around me.

**Comment by ArmaniKida** [comment]
Yes I have already installed MacOS on a hard drive working but trying to boot one day and it’s stuck on the apple and progress it first shows on boot. Just using my Windows boot from open core rn .

**Comment by SchmockLord** [comment]
You shouldn't boot to windows from OC because the ACPI patches are enabled then and some devices are not detected properly then.

To boot macOS you should add bootargument "-v" to the bootargs and share a picture of the screen where it is stuck. Are you using the Vision D?
