### ISSUE TITLE
InstallAssistant crashes during installation.

### ISSUE THREAD

**Issue by nonnumericdave** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#22]
I'm currently using the same exact motherboard and processor as the repository, and I'm seeing a segfault in InstallAssistant.  It seems as though it is crashing in CFGetTypeID(...), although I can't be 100% certain, as I don't have exported symbols for InstallAssistant, but I'm fairly certain the crash is occurring in CoreFoundation.

I'm using the same EFI as the repository, with the requisite serial number, etc., modifications.  I've tried USB installers created with both MacOS Catalina 10.15.4 and 10.15.5, and I see the same exact crash.  The USB installer boots up fine, I get to the point where I run the installer, and it just crashes.  I've attached a photo of the callstack crash log.

![InstallAssistantCrash](https://user-images.githubusercontent.com/219625/85227929-8ae93c80-b39d-11ea-93d1-e7f9cef7aaa7.jpg)

**Comment by nonnumericdave** [comment]
Just as a follow-up to this issue, I was finally able to install MacOS without the InstallAssistant crash.  The issue appeared to be related to the Corsair Commander Pro that I had connected via one of the internal USB headers.  Removing this internal connection *prior* to the installation process appears to have resolved the issue.  The solution was ultimately discovered at the follow location:

https://www.insanelymac.com/forum/topic/343838-new-install-issues/

**Comment by Jimbojingle** [comment]
Hi,

I was intending to use a Commander Pro in my build. Is there no solution to this problem or can the Commander Pro just be disconnected while installing Catalina?

**Comment by nonnumericdave** [comment]
> Hi,
> 
> I was intending to use a Commander Pro in my build. Is there no solution to this problem or can the Commander Pro just be disconnected while installing Catalina?

I only disconnect the Commander Pro during the installation from USB.  Once I had MacOS installed to the intended drive and had the EFI copied, I reconnected the Commander Pro.  However, if you take a look at the aforementioned link, the user mentioned that MacOS was mistakenly interpreting the Commander Pro as a power supply.  I'm seeing the exact same issue, but it doesn't appear to cause any problems (at least that I care about).

**Comment by Jimbojingle** [comment]
Thanks, That's useful to know.

I would be interested in how you have your Commander Pro connected and configured and whether you are using Corsair Link. I intend to configure a full RGB setup using Corsair RGB Ram, Fans, Cooler and Power Supply. Don't really want to use up too many USB headers. I am also using the Fenvi FV-T919 card for Wifi/Bluetooth which uses another USB header.
