### ISSUE TITLE
OC 0.8.1 issues?

### ISSUE THREAD

**Issue by crashmaster4000** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#224]
First off - thanks for the fast update! 

Quick questions - There are three errors that pop up:
OCS: No schema for SerialInit at 6 index, context
OCS: No schema for AllowNvramReset at 0 index, context
OCS: No schema for AllowToggleSip at 2 index, context

I'm guessing from the latest changes the config.plist needs to be updated.

Also, this starts off with the text interface not the graphical version of OpenCore.

And finally... I can't remember. Getting over Covid and wow my mind is foggy. Will update this when I can recall what I was thinking.

Thanks again - you're awesome!

crash

**Comment by SchmockLord** [comment]
Damn. I knew this issue and thought I have cleaned it up.

This comes from opening the config.plist files with OCAuxiliaryTools. This tool does some things good, but has some flaws like putting schemas in the config that are not in OC 0.8.1 anymore, although it is in OC 0.8.1 mode.

I will clean this up and reupload it again.

**Comment by SchmockLord** [comment]
Update: That is weird. I have released after I have made the commits without these Schemas but they are still in the release.

Will do a fresh release.
