### ISSUE TITLE
Getting OpenCanopy working in 0.8.1

### ISSUE THREAD

**Issue by crashmaster4000** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#227]
Please delete if obvious.   I had to download the Resources files from https://github.com/acidanthera/OcBinaryData and replace the "Images" folder for the GUI boot screen to work. I just replaced the whole folder located in EFI -> OC -> Resources

Hope this helps someone!

**Comment by SchmockLord** [comment]
Definitely. Thanks. I tried yesterday and replaced the Resources folder with the one with my Z590i EFI which is working fine but it still wasn't working. Then I tried downloading it fresh from the GitHub you mentioned, but still the GUI wasn't working. Will update the repo soon.

**Comment by SchmockLord** [comment]
Replaced OpenCanopy.efi again with the newest ones from OC 0.8.1. Now GUI Bootloader should work again.
