### ISSUE TITLE
There should be five items of energy saving, I hope there are five items of energy saving

### ISSUE THREAD

**Issue by mmeiwenlong** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#23]
Come on 
![Energy-saver-settings](https://user-images.githubusercontent.com/44661424/85228729-b446ae80-b417-11ea-9e46-ca4660be00cb.png)

**Comment by jamesfawcett** [comment]
Not sure what you're asking here, this is my screenshot from my genuine mac (although a laptop), it still has the same four checkboxes: 
![image](https://user-images.githubusercontent.com/5245272/85426353-42cf4300-b572-11ea-924b-14463d65b805.png)

**Comment by miip** [comment]
Mine looks like this:
![energy](https://user-images.githubusercontent.com/7153898/85429083-7d3edd00-b57e-11ea-89ab-7c9e9bdfbe71.png)

**Comment by SchmockLord** [comment]
Maybe just different OS-versions?

**Comment by miip** [comment]
This is Catalina 10.15.5, should be the same as yours. 
I am using the same Hardware but followed https://www.tonymacx86.com/threads/gigabyte-z490-vision-d-thunderbolt-3-i5-10400-amd-rx-580.298642/ for the install.

![version](https://user-images.githubusercontent.com/7153898/85441893-debb7780-b58f-11ea-9075-f426852ea71a.png)

**Comment by mmeiwenlong** [comment]
> 也许只是不同的OS版本？

This five items of energy saving are generally only available in the imac model series. The macbook pro series only has four items of energy saving. I think your desktop computer will not be set as a macbook pro model. If your model is set to the imac series, there will be  Five items of energy saving, no five items can only show that some places have been obtained.  If you need this SSDT-PM.aml, there are generally five items. (The fifth item "Restart after power off" also needs to load PPMC and PMCR under LPCB to appear.)
