### ISSUE TITLE
OC 0.8.2 macOS Ventura Experimental

### ISSUE THREAD

**Issue by SchmockLord** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#230]
Hi guys,

I have created a macOS Ventura EFI based on the current Nightly Build of OC 0.8.2.

It works fine on my Z590i.

@jamesfawcett @g3d @crashmaster4000 You volunteered to test future updates :) Can you try this? Of course it would be nice if someone could test it with Ventura, but also backwards compatibility with macOS Monterey would be nice to know.

[EFI_OC082_macOS-Ventura_Experimental_v1.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/8907879/EFI_OC082_macOS-Ventura_Experimental_v1.zip)

**Comment by crashmaster4000** [comment]
Morning!  I'm about to head off to work but I'll install it when I get home and let you know the results. 

Thanks!
crash

**Comment by g3d** [comment]
Would check it this evening on Ventura and circle back.

**Comment by g3d** [comment]
![Screen-Shot-2022-06-15-20-56-04](https://user-images.githubusercontent.com/859210/173893554-726cfad9-37e2-4156-8c81-0d4f3b2cbbf7.png)

Worked without significant problems. Ethernet still working. Reset NVRAM option back to menu. No boot loops or other issues/glitches that are visible after EFI updates.

**Comment by jamesfawcett** [comment]
That's great! I will test this out Friday, I am contracting this week. Hope not too late for you! :)

**Comment by crashmaster4000** [comment]
Ok just got home, made a fresh flash drive with the efi folder from the first post, rebooted, selected it and Monterey started to boot then hung. I have an Exchange email server migration starting at 5PM (25 minutes from now) and when it’s finished (god knows when…) I will poke around and do some troubleshooting.

Wish me luck - these migrations never go smoothly.

crash

**Comment by SchmockLord** [comment]
@crashmaster4000 I didn't get what you tried. Did you try to just boot into your existing Monterey and it doesn't work with my EFI or did you try to install Ventura and it didn't work?

**Comment by crashmaster4000** [comment]
Morning Chris and sorry for the rushed comment. I created a new USB disk with your EFI folder on it and attempted to use that to boot an existing install of Monterey. One thing I noticed is (it’s 5:30am… so might have seen the wrong thing) the boot.efi file had a creation date of 2021 on it. Not sure if that’s causing the issue. When I get home I’ll play with it some more.

**Comment by g3d** [comment]
The only problem I noticed on Venture was that boot & start of the apps take longer than on previous version of EFI.

**Comment by SchmockLord** [comment]
@crashmaster4000 The only thing I changed that could cause these issues is setting DevirtualiseMmio to false. Set it to true again.

After that you can try to set bootargs like @g3d : -wegbeta -lilubetaall -vsmcbeta -alcbeta

And please add -v and post where it hangs.

My first thought was: Maybe you are using iGPU-based config which I heard is causing issues with Ventura. But as you were still trying with Monterey I cannot really explain why this config should be an issue.

**Comment by SchmockLord** [comment]
@g3d Try SetApfsTrimTimeout=0. For me this is much faster at boot. Gives me 30sec. But I am still not sure if this totally turns of Trim or just at boot. If it totally disables trim, then this can lead to data loss issues longterm.

**Comment by crashmaster4000** [comment]
Ok just made your suggested modifications and it hangs at:

Virtual Boot IONVMEControlller :: start (IOService *) ::775 IONVMeController :: start

Open to anything you’d like me to try.

crash

**Comment by SchmockLord** [comment]
I think this is related to VirtualSMC. You can try to disable the SerialIO and Processor satellite kexts. Or if this doesn't work try bootarg vsmcgen=1.

**Comment by crashmaster4000** [comment]
Ok tried the first and no difference did the second and now got this:
“AppleKeyStore:863:0: oy vey”

Let me know if you think of anything else to try…
Crash

**Comment by DeJoTaDeEmE** [comment]
Thank you, I have been able to install ventura beta 2 with this EFI, thank you very much, I had to use the installer terminal and put this:

/Volumes/Image\ Volume/Install\ macOS\ Ventura\ beta.app/Contents/Resources/startosinstall --volume /Volumes/"name of volume to install"

with the EFI 0.81 now suddenly the system takes a long time to start, when before it took very little, I have not changed anything with the EFI 0.81 I don't know why this happens now,

thank you anyway

**Comment by crashmaster4000** [comment]
Afternoon!

Not sure what changed but I was able to succeed in booting off the latest 0.8.2 and no problems so far. I’ll keep testing and see if I can break anything.

Quick question - what’s the suggested version of the BIOS to use? If it’s not broke don’t upgrade it…. Maybe….

Thanks!
Crash

**Comment by g3d** [comment]
I had to upgrade for pre-release of 0.8.3 in order to install Ventura b3
