### ISSUE TITLE
macOS Ventura 13.0 official version does not support

### ISSUE THREAD

**Issue by sbfkcel** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#238]
The official version of macOS Ventura 13.0 is not supported, but the test version is possible.

**Comment by a-melon-007** [comment]
@sbfkcel That's not true. I'm currently running macOS Ventura 13.0. Everything is working except DRM videos from Netflix and Disney+ (in Safari) and Sidecar.

**Specs:**
- Intel i9-10850K
- Gigabyte Z490 Aorus Elite AC:
	- Audio: Realtek ALC1220
	- 2.5Gbit Ethernet: Realtek RTL8125AG
	- One USB-C Header
- RAM: 4x16GB G.Skill AEGIS Z 3200Mhz CL16-18-18-38 1.35V
- GPU: Sapphire Radeon RX 5700 XT Nitro+ Special Edition
- Wi-Fi/Bluetooth: MQUPIN Fenvi T919 Wireless Card with BCM94360CD
- OS: MacOS Ventura 13.0
- System Type: iMac20,2
- OpenCore: [v0.8.6](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.8.6)

**Comment by jamesfawcett** [comment]
![image](https://user-images.githubusercontent.com/5245272/205308799-a972501f-edc2-402e-ac4b-141cf58d2cc0.png)


I've upgraded through all versions, test and official, no issues. Which SMBIOS are you using?

**Comment by sbfkcel** [comment]
My system is damaged. You can reformat the disk.
