### ISSUE TITLE
MacOS Ventura 13.0.1 - Issue playing videos

### ISSUE THREAD

**Issue by hsotnikcah** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#240]
Video freezes every 10 seconds after upgrading from MacOS 12. Tested with mp4 files (different players) and Youtube videos.
It starts after 10 min system startup. Before that, its fine.

System:
- z490 Vision D
- i9 10850K
- Radeon Sapphire 6600 XT
- iMac 20,2

**Comment by hsotnikcah** [comment]
Fixed by removing the iGPU device-ID 923E0000.
MacOS will change the device-ID to 0x9BC50003 (=0300C59B).

I noticed less activity of the iGPU in Intel Power Gadget. Not sure, if this will decrease performance but no issues with playing videos anymore.

**Comment by jamesfawcett** [comment]
Thanks @hsotnikcah I'm having the same issue with my 6900XTX. It didn't happen on Ventura Beta. Will test out your fix today.

**Comment by jamesfawcett** [comment]
@hsotnikcah thanks videos are now working for me too, with my 6900XTX

Activity within Intel Power Gadget seems about the same before and after:

![image](https://user-images.githubusercontent.com/5245272/204783712-df2a1547-8e26-47b3-83a1-19a7f45ff62b.png)

![image](https://user-images.githubusercontent.com/5245272/204783850-b855f6d4-6b42-402e-9afb-b836f678a80b.png)

I have a different graphics card to you, my device properties for that are:

<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Internal@0,1,0/0,0/0,0/0,0</string>
				<key>device-id</key>
				<data>v3MAAA==</data>
				<key>model</key>
				<string>Radeon RX 6900 XT (XTXH)</string>
			</dict>

Maybe this will help someone else too. 

Thanks
James

**Comment by fgz-cat** [comment]
Same error here, and @hsotnikcah 's fix solved the issue.
Thanks a lot @hsotnikcah !

**Comment by fgz-cat** [comment]
More information on this.
Before I applied @hsotnikcah 's fix, I could not play any video without it freezing every X seconds.
After the fix, the playback in VLC, youtube, or other applications like Gather was normal. 
However, some embedded videos on Instagram, Twitter or Facebook on Chrome were still freezing, and Chrome was not responding during those freezes.
I disabled hardware acceleration on Chrome, and videos seem to be playing fine now.

**Comment by fgz-cat** [comment]
In the end, none of the previous fixes worked.
However, I was able to completely resolve the problem, and activate hardware acceleration again, by using the iMac Pro config file. I was previously using the iMac config.
Haven't updated to the new release yet though.

**Comment by hsotnikcah** [comment]
Was thinking about switching the SMBIOS as well but would like a solution with longer MacOS support.. (iMac Model is a newer build and will be most likely longer supported..)

**Comment by hsotnikcah** [comment]
I'm on 13.2.1 now and didn't experience any issues anymore. Switched back to the recommended device-ID 923E0000. Works fine for now.
