### ISSUE TITLE
NVMe SSD Support

### ISSUE THREAD

**Issue by Jimbojingle** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#25]
I have all the components to build this system now.

I was going to purchase the Samsung Evo Plus NVMe SSD but I believe that that is only PCIe 3.0 compatible.

Should I be looking at something like a Sabrent Rocket NVMe SSD which has PCIe 4.0 support?

Am I right in saying that the Z490 Vision D does not support PCIe 4.0 with an Intel 10th Gen CPU but it will with 11th Gen CPU?

At least this would allow some future proofing!

**Comment by SchmockLord** [comment]
If the price difference is not that high, I would purchase a PCIe 4.0 SSD.

There is a chance that intel will unlock PCIe 4.0 capabilities of this board, although we are talking about Intel and a very small chance ;).

And I don't think this board will support a 11th Intel CPU.
