### ISSUE TITLE
Audio and Video Stutter after RX6800xt upgrade

### ISSUE THREAD

**Issue by spamilton1** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#260]
I've been running a system for a while stably on an RX580, but wanted to update to a RX6800XT. Since doing the change, had a number of issues creep up including studdering audio on my USB audio card (Motu 8Pre) and fullscreen youtube glitches out the monitor a lot. 

I did add the Pikera bootarg, but currious if there's other items I need to adjust

**Comment by SchmockLord** [comment]
In which Version of my repo are you and which config are u using? iMac w/o iGPU or iMacPro?

**Comment by spamilton1** [comment]
I'm using the one for OC0.9.2 iMac W/o iGPU

**Comment by spamilton1** [comment]
I've also tried adding the bootarg radnoaudio (saw it elsewhere as a cure), but I don't think it's helped.

Also if it's relevant, both my monitors are using DisplayPort connections, but neither is part of the audio system, I just run audio through my Motu USB interface.

**Comment by SchmockLord** [comment]
Try a different USB port and cable. To me this sounds like you are using a port that falls back to USB2 and then the bandwidth or power delivery is not keeping up. I also had these issues with my MOTU M2 and also with my vocaster One.

**Comment by spamilton1** [comment]
So, I've now tried a number of ports and different cablese and this issue continues with only the hackintosh. When I boot into windows on the same machine, no problems. 

I'm wondering if there's something in the USB here that's off or if I need to explore a PCIE usb card

**Comment by spamilton1** [comment]
Good news, I got it stable again, it was in fact my USB issues, solved by using the DAC USB port at +0.2V and now it's stable
