### ISSUE TITLE
both GPU not detected

### ISSUE THREAD

**Issue by kaisarantonn** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#27]
i am using your EFI folder for catalina and All of your guide
but i delete the radeonboost.kext

i7-10700k
Sapphire radeon 5700xt Nitro+
Gigabyte z490 Vision D
Corsair Vengeance 4x8gb 3200mhz - XMP profile 1
i dont use fenvi or external wifi PCI adapter, i use ethernet, i have no problem with network

i followed your guide but delete the radeonboost.kext
i do snapshot OC, save, and boot, 

system report only the 3700x recognized
and in videoproc they are both not detected all 
please help kindly

![Screen Shot 2020-06-30 at 04 24 13](https://user-images.githubusercontent.com/60268411/86057552-92899f00-ba89-11ea-9086-fc5ef613b735.png)

**Comment by SchmockLord** [comment]
Use the config.plist with SMBIOS=iMacPro1,1. Disable your iGPU in BIOS. And delete the PciRoot(0x0)/Pci(0x2,0x0) device.

**Comment by kaisarantonn** [comment]
> Use the config.plist with SMBIOS=iMacPro1,1. Disable your iGPU in BIOS. Add bootarg "agdpmod=pikera". And delete the PciRoot(0x0)/Pci(0x2,0x0) device.

I already use agdpmod=pikera since i install.

Pardon me, 
So the step is
1. Mount EFI
2. Edit the deviceproperties from iMac19,1 to iMacPro1,1
3. Delete PciRoot(0x0)/Pci(0x2,0x0) device 
4. At Bios igpu auto > disable

Correct? Is that deleting the PciRoot(0x0)/Pci(0x2,0x0) device will only left me with radeon gpu only? 

I want to enable the intel hardware acceleraton too because quick sync saves time in rendering

**Comment by SchmockLord** [comment]
Yes, all steps are correct. But you should also generate new serials then. 

Yes, disable the iGPU. With a powerful GPU like you have it is better to use the Radeon GPU only. It is faster in renderings than with quick sync enabled. I have tested it.

**Comment by kaisarantonn** [comment]
> Yes, all steps are correct. But you should also generate new serials then. 
> 
> 
> 
> Yes, disable the iGPU. With a powerful GPU like you have it is better to use the Radeon GPU only. It is faster in renderings than with quick sync enabled. I have tested it.

Yeah but my question is how do i enable it so even videoproc will detect?

**Comment by kaisarantonn** [comment]
@SchmockLord 
i cant get premiere pro hardware encoding
my bootflag 
shikigva=80 darkwake=8 agdpmod=pikera
![Screen Shot 2020-07-01 at 04 19 14](https://user-images.githubusercontent.com/60268411/86178550-ba910500-bb52-11ea-8121-a906043d5a31.png)

![Screen Shot 2020-07-01 at 04 14 30](https://user-images.githubusercontent.com/60268411/86178535-b533ba80-bb52-11ea-898a-27c70575f416.png)

lilu and WEG are installed as your folder too,
where does it get wrong? kindly please help

**Comment by SchmockLord** [comment]
Just do the steps I mentioned above.

iMacPro1,1 instead of iMac19,1.

Disable iGPU in BIOS (not Auto).

You see this?: I am using dGPU only and iMacPro1,1.
![Screenshot 2020-06-30 at 23 49 12](https://user-images.githubusercontent.com/19785918/86180386-4f343c80-bb2c-11ea-8bbb-80e56738a9d9.png)

**Comment by kaisarantonn** [comment]
@SchmockLord Damn you are a lifesaver! great thanks!
altough i did blocked several times because generating gensmbios, i managed get 1 and seems the purchase date hasnt been validated yet

![Screen Shot 2020-07-01 at 05 36 20](https://user-images.githubusercontent.com/60268411/86183849-1791b880-bb5d-11ea-8b6e-27491f8fd263.png)

**Comment by SchmockLord** [comment]
You are welcome.

**Comment by hilen** [comment]
@kaisarantonn Can you share the efi folder? Mine is 5700xt too, but I don't know how to replace the value in the config.plist. Many thanks.
