### ISSUE TITLE
Where to put the darkwake boot argument?

### ISSUE THREAD

**Issue by stuzor** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#28]
Hello and thanks for the guide, this hackiontosh has been so freaking easy with all your hard work! I am also running the Gigabyte Vision D board and am trying to figure out where do I apply the darkwake = 8 boot argument. Apologies for such a basic question but I am a opencore noob and still trying to transition my understanding from clover. 

In the config.plist I see "booter" instead of boot. I tried it there under quirks as a number but it didn't work. I used clover configurator to apply it as well but it created another entry called "boot" in the plist and wasn't sure if this would be compatible.

**Comment by SchmockLord** [comment]
Thank you. 

You can add bootarguments in the following structure: NVRAM - Add - and then the third one that starts with 7. 

There you should find a bootargument item. Just try darkwake=8 or 0. These worked best for me.
