### ISSUE TITLE
iPhone does not work over thunderbolt ports or motherboard usb-c port

### ISSUE THREAD

**Issue by sebastienb** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#29]
When I plug my iPhone in the motherboard thunderbolt ports or on the motherboard usb-c port it does not show in finder. If i use any of the regular usb ports it works. I've tried hard drives and even my camera on the usb-c and thunderbolt ports and they work.

**Comment by SchmockLord** [comment]
When I open Hackintool without any USB-configuration it has 21 ports without counting the Thunderbolt ones (SSP1, SSP2).
macOS only supports 15 ports. So you have to find compromises.

Initially I wanted to have more ports to plug my USB-devices in. And compromised e.g. on the USB2 support on a USCB port. That is why your iPhone/iPad is not shown when you plug it into the USBC ports.

But I have created an alternative USB-configuration. The two USB2 ports on the back and the internal USB2 header doesn't work in this configuration. Therefore the USB2 support on USBC ports.

You can try that and tell me how it works for you:
[SSDT-UIAC-alternative2-USB-mapping.aml.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/4896645/SSDT-UIAC-alternative2-USB-mapping.aml.zip)

**Comment by sebastienb** [comment]
Thank you!
