### ISSUE TITLE
Ethernet connects and disconnects issue

### ISSUE THREAD

**Issue by nyichiban** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#32]
Used your kexts for the Intel i225 and on my board, Asus z490i-gaming the connection connects then disconnects every few seconds.

**Comment by SchmockLord** [comment]
You have to find the correct PCI-path for your ethernet port. I can show you, but this requires a Skype/teamspeak session.

https://www.patreon.com/SchmockLord

**Comment by nyichiban** [comment]
I did put in the correct pci-path and had the device is set to what others mentioned f2150000

**Comment by nyichiban** [comment]
Do I need intelmausi kext if I have the fakepciid and fakepciid225 kext?

**Comment by nyichiban** [comment]
Fixed it! For some reason it put it on energy efficiency and changed it to full duplex and it worked. Thanks for the Kext btw!
