### ISSUE TITLE
Has anyone tried the bios update? there is a version F5d that was released on 2‎020/07/09

### ISSUE THREAD

**Issue by sebastienb** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#34]
https://www.gigabyte.com/Motherboard/Z490-VISION-D-rev-1x/support#support-dl-bios

It list these as changes:

Improve AORUS Storage Manager support for AORUS RAID SSD 2TB, convenient user operation experience
Improve RGB DDR compatibility

**Comment by dehjomz** [comment]
Bios f5d is a worthy upgrade. The GUI changed, plus, Gigabyte finally enabled option to disable CFG-lock in the bios, just like MSI, and ASRock have had for years.

**Comment by sebastienb** [comment]
Thanks, updated and so far all is working.

**Comment by hcintegrity** [comment]
Hello, 
successfully upgraded to F7c.
