### ISSUE TITLE
Audio not working through ports

### ISSUE THREAD

**Issue by charanjeet5ingh** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#35]
Hi, I am using the AppleALC.kext, FakeID.kext, FakePCIID_Intel_HDMI_Audio.kext and i also sat the following DeviceProperties

`<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>device-id</key>
				<data>cKEAAA==</data>
				<key>layout-id</key>
				<data>BwAAAA==</data>
			</dict>
		</dict>
	</dict>`

and my nvram boot-args are alcid=11. My hdmi audio is working but no audio from the back panel and frontpanel. Can you please suggest me what to do.

**Comment by hilen** [comment]
Do your microphone works fine?
