### ISSUE TITLE
Internet speed capped at 100mbps

### ISSUE THREAD

**Issue by henryxrl** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#36]
Hello,

I have the exact same hardware as yours. Everything works except that the internet speed is capped at 100mbps. I think this is because the ethernet port (i-225V, the 2.5Ghz port) is automatically set as the following:
![image](https://user-images.githubusercontent.com/7662954/88375743-1faed380-cd6a-11ea-8189-a359ae497d75.png)

So I tried manually set the speed to 2500Base-T as below:
![image](https://user-images.githubusercontent.com/7662954/88375802-3fde9280-cd6a-11ea-99b2-237b42b72524.png)

After the setting, the wifi speed went up 5 times! But the weird thing is that this ethernet port can no longer connect to the internet, even after I manually set all the IP address, DNS server etc. Basically this means that my ethernet can't work, though wifi speed is not capped any more.

I also tried to switch back from 2500Base-T to 100Base-TX (the default setting). Now ethernet works, but speed goes back to be capped at 100mbps.

Are you aware of similar issues? Could you please check your internet speed and also the speed and duplex settings for your ethernet?

**Comment by SchmockLord** [comment]
I would say this is an issue on your site and doesn't have to do anything with the Hackintosh or your PC. I think it is more network related issue.

I guess it only detects 100Mbps because the other end of the cable or the cable itself doesn't deliver more.

Mine is connected to a 10Gb NAS and is detected as follows:

![Screenshot 2020-07-24 at 11 05 38](https://user-images.githubusercontent.com/19785918/88376549-ec863780-cd9d-11ea-94d6-1afdd77e232c.png)

**Comment by henryxrl** [comment]
Yeah, maybe it's the router. I'm using Verizon Fios fiber from the U.S. The following settings made my speed back to 900+ Mbps:
![image](https://user-images.githubusercontent.com/7662954/88420023-31b56400-cdb4-11ea-9fe8-b8f90a805283.png)

Hope people with similar issues find this useful. Thanks!

**Comment by SchmockLord** [comment]
Why don't you set it to 
Manually
Full duplex
2500
?

**Comment by henryxrl** [comment]
If I set that way, the wifi speed is around 500 Mbps, which is fine for a 1Gbps network. But, the ethernet will no longer be working - it'll show as "not connected" for some reason.

**Comment by kellertobias** [comment]
it's because your router probably only supports only 1000baseT. If you tell your card to speak 2500base-T, your router does not understand your hackintosh's data packets and thus think there is no device connected.

**Comment by bugsplat490** [comment]
@henryxrl  Just as another data point my hardware shows as `1000Base-T` and I tested it with speediest.net and I was getting 670Mbs down and 426Mb/s up so I don't think this is a limitation of the hackintosh configuration and more as has been noted a router configuration issue.
