### ISSUE TITLE
NVRAM support

### ISSUE THREAD

**Issue by msigut** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#4]
Please, could you desribe NVRAM set-up process?
- Is necessary to unlock MSR (like 0xE2 settings for Z390 and BIOS: F8+)
- Is possible to use same SSDT-NVRAM.aml? (again as Z390)

Thank you for all ... great work :)

**Comment by 99electronic** [comment]
I did unlock MSR on vision D motherboard same as on z390 designare board. I did not try it without it (I unlocked before I started following this guide)

**Comment by SchmockLord** [comment]
I have native NVRAM-support without any SSDT-NVRAM.aml.
