### ISSUE TITLE
Are you currently using Big Sur or Catalina?

### ISSUE THREAD

**Issue by jamesfawcett** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#44]
Hi @SchmockLord 

Could I just ask are you currently using Big Sur full time or just testing it out? 

I use my Catalina build using your setup full time, its working fantastic now. I stopped copying your changes when you made the leap to Big Sur. Is it still in Beta? 

I don't want to be left behind, I can see you making lots of improvements in the releases! 👍 
Ps just signed up as Patron Tier 1

thanks 
James

**Comment by SchmockLord** [comment]
Hello James,

yes, I am using Big Sur full-time 8h-12h a day, 7 days a week :).

I think you can definitely try the newer version of my config. It works for me in Catalina 10.15.6 too.

Just try my newest EFI-folder from a USB-stick and replace the serials with yours. If it is not working, stick with your current.

**Comment by jamesfawcett** [comment]
Awesome! That's what I'll be doing tonight after work then thanks! I applied the Lilu update earlier and all good. 

I would like to try out the iGpu fixes mentioned here next: https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/issues/40

I haven't yet been able to get your Intel UHD settings working for mine. I have your device `PciRoot(0x0)/Pci(0x2,0x0)` in my config.plist but in my devices I don't actually have a Pci(0x2,0x0) - is that device emulated from WhateverGreen? 

![image](https://user-images.githubusercontent.com/5245272/89197303-69d25900-d5a3-11ea-9775-36a7ca8bc06b.png)

Thanks again for getting me started in the OpenCore world! I have an old ThinkPad X201 running Clover, I've just changed from High Sierra to Catalina, I really want to convert that to OpenCore next project :) https://github.com/jamesfawcett/Thinkpad-X201-Hackintosh-Catalina

**Comment by SchmockLord** [comment]
You should also switch to SMBIOS iMac19,1 if you want to use your iGPU. And of course, need to enable the internal graphics in the BIOS.

**Comment by jamesfawcett** [comment]
Cool! That's now all working! :) It just needed enabling in the bios (It was set to Auto, I changed to Enabled). 

Your latest EFI works great on my system too. I transferred across my **PlatformInfo** and **DeviceProperties**. 

![image](https://user-images.githubusercontent.com/5245272/89199731-e581d500-d5a6-11ea-9cd5-a9fce3953b91.png)

Thanks again 👍  Everything working
