### ISSUE TITLE
GUI boot menu

### ISSUE THREAD

**Issue by samparhizkar** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#45]
Is it possible to add GUI boot menu to this repo?
I ask this because In my setup i have magic keyboard and a logitech mouse (with usb dongle). Now without the GUI boot menu i basically have to have my keyboard plugged in just because of that. But I noticed the GUI works pretty good with the mouse so I can use the keyboard wireless. Aside from that it looks slick!

**Comment by sebastienb** [comment]
It's not difficult to setup using this guide https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui

**Comment by bugsplat490** [comment]
@sebastienb I tried this just now, and following the instructions above in dortania I could not get this to work. Does anyone else have this working? I did wonder since I used the latest version of this repo and it says in the files that OpenCore 0.6.1 is being used in the commit messages, yet there is as yet no OpenCore 0.6.0 release. I also noticed that the guide in dortania said that the exact version of OpenCanopy.efi had to match the version of OpenCore. So a mismatch might still be occurring?

**Comment by sebastienb** [comment]
Sorry i recently switched to .6.1 and di not take the time to setup open canopy.

**Comment by bugsplat490** [comment]
@sebastienb Just to update this following the [dortania guide](https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui) I got this to work. One other thing I did was set UIScale to 2 [see option here](https://dortania.github.io/OpenCore-Post-Install/cosmetic/verbose.html#macos-decluttering). The default setting of 1 kept everything so small that the labels were very hard to read. But now I have a nice graphical boot picker!

**Comment by samparhizkar** [comment]
@sebastienb can you do a pull request to add it to this repo ?

**Comment by bugsplat490** [comment]
@samparhizkar @sebastienb @SchmockLord 

I am happy to put in a PR with this change, but do we want to split it out into a seperate EFI folder, or just put it straight on top of the existing EFI folder. (Chris has kept a really nice minimally clean EFI folder and this will be "bloating" it.)

I can imagine changing from:

```
Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D ❱ tree -LC 2
.
├── BIOS-settings
│   └── ...
├── Benchmarks
│   └── ...
├── Docs
│   └── ...
├── EFI
│   ├── BOOT
│   └── OC
├── README.md
├── TechnicalNotes.md
├── USB-Port-Configs-Gigabyte-Z490-Vision-D_v1.pdf
├── USB-Port-Configuration.md
└── bios-settings.md
```

to something like:

```
Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D ❱ tree -LC 3                                     master via 🅒 conda-env
.
├── BIOS-settings
│   └── ...
├── Benchmarks
│   └── ...
├── Docs
│   └── ...
├── FullEFI
│   └── EFI
│       ├── BOOT
│       └── OC
├── MinimalEFI
│   └── EFI
│       ├── BOOT
│       └── OC
├── README.md
├── TechnicalNotes.md
├── USB-Port-Configs-Gigabyte-Z490-Vision-D_v1.pdf
├── USB-Port-Configuration.md
└── bios-settings.md
```

Actually in the FullEFI I would try and get the boot up chime going as well?

**Comment by samparhizkar** [comment]
@bugsplat490 I would say keep the chime off to keep it inline with how new macs work by default. As for proposed folder structure its ok but will it automatically keep up with the changes that Chris and other maintainers at to it in the future or its something that needs to be maintained separately every time? if it's the latter case I wouldn't consider it bloat to merge with main EFI because again it would look close to how mac's boot menu looks like and thats the goal of the hackintosh project.

**Comment by bugsplat490** [comment]
You are correct that these would need to be kept in sync if we have seperate versions. It would be cleaner to have the single folder but of course with more things, there are more things to go wrong...

I am fine with having a single EFI folder if @SchmockLord Chris would prefer that. 

Chris do you have a preference here? I see the options as:

  1. Clear instructions on how to add to the current setup (basically everybody that wants a graphical launcher adds it themselves)
  2. Seperate FullEFI and MinimalEFI folders
  3. Incorporate the OpenCanopy graphical launcher into the one combined EFI folder

**Comment by SchmockLord** [comment]
I would prefer option 1 because it already is hard for me to keep the different configs in sync (you also have to keep in mind, that I have to sync the ones I share here with the one I am evolving for myself with my serials etc.).
And I mean adding the GUI is mainly one option in the config and copying the icon folder.

**Comment by bugsplat490** [comment]
@SchmockLord Thanks Chris, I had a feeling that this might be the case (or you would likely have already done it...) I'll fill out the documentation a little to include this. Thanks!

**Comment by SchmockLord** [comment]
Hey @samparhizkar @bugsplat490 @sebastienb 

I have included the GUI bootmenu and the chime sound in my current version. I think this should make some of you happy :)

**Comment by bugsplat490** [comment]
@SchmockLord Thanks Chris!!
