### ISSUE TITLE
After initial boot screen, the installer doesn't go to installing MacOS

### ISSUE THREAD

**Issue by Nishant-Kathil** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#47]
I got the latest EFI download OC 6. After initial install selection page, it doesn't go to installation process. Any suggestions would be helpful?

I have the exact same hardware configurations.
Motherboard - VisionD
CPU - 10900K
Memory - Corsair DDR4 3600 2*32
Graphics - Sapphire 5700XT Nitro+
Storage - ADATA SSD
BIOS - F5

I changed the config.list to print verbose messages during boot. After initial boot screen it doesn't go anywhere

I have kept the the internal graphics as Enabled

**Comment by Nishant-Kathil** [comment]
I have the exact same hardware configurations. 
Motherboard - VisionD
CPU - 10900K
Memory - Corsair DDR4 3600 2*32
Graphics - Sapphire 5700XT Nitro+
Storage - ADATA SSD

I changed the config.list to print verbose messages during boot. After initial boot screen it doesn't go anywhere

**Comment by jamesfawcett** [comment]
Hi @Nishant-Kathil I think one of the last updates to the files was to remove RadeonBoost kext ad the entry in the config.plist, is that what you need?

**Comment by Nishant-Kathil** [comment]
> Hi @Nishant-Kathil I think one of the last updates to the files was to remove RadeonBoost kext and the entry in the config.plist, is that what you need?

SchmockLord has disabled RadeonBoost for AMD Navi and I am using 5700XT which is Navi. I don't think I need it. There is something else going here.

I don't get any error *.txt file as well. After initial boot it doesn't go anywhere.

**Comment by Nishant-Kathil** [comment]
Sorry, I am an idiot. It works perfectly now. Thank you very much @SchmockLord 

I was using Motherboard HDMI port and it didn't displayed anything. I connected the HDMI to AMD GPU and it started showing the install process. Thanks again

I am closing this issue.

@SchmockLord - I read TonyMac and seems like CaseyJ was able to resolve the iGPU with new WhateverGreen.kext. I will wait for the next EFI. You are doing great work. Thanks again
