### ISSUE TITLE
Documentation: which BIOS is used

### ISSUE THREAD

**Issue by bugsplat490** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#48]
In reading through the guide it wasn't clear to me which version of the BIOS for the vision D gigabyte motherboard was being used.

In the BIOS settings screen shots the screen shot for "System Info." was not present.

I am guessing the "overall hackintosh system" works indepdendent of the BIOS version but it would be nice to document that in the guide. I have BIOS F3 for what it is worth and I was intending to upgrade to BIOS F5 but wanted to check... Thanks in advance! (And thank you *so much* for your efforts in documenting this whole process!)

**Comment by addisonduda** [comment]
I upgraded to F5 two weeks ago and it's been working great. I would definitely recommend getting F5 just so you stay up-to-date. The GUI for F5 is a bit different than shown in the images for the BIOS settings, but you should be able to navigate just fine.

**Comment by jassingh9** [comment]
I upgraded to the latest F5 and highly recommend doing so, the UI looks a little different, but the options remain the same and the BIOS now has an option to disable CFG Lock without using the CFG unlock tool.

**Comment by phao5814** [comment]
> I upgraded to the latest F5 and highly recommend doing so, the UI looks a little different, but the options remain the same and the BIOS now has an option to disable CFG Lock without using the CFG unlock tool.

@jassingh9 Thanks so much for confirming CFG Lock can now be disabled. Would you mind confirming the model of your motherboard? [Is this the one](https://www.gigabyte.com/Motherboard/Z490-VISION-D-rev-1x#kf)? Also curious to hear which CPU you went with.

**Comment by jassingh9** [comment]
> > I upgraded to the latest F5 and highly recommend doing so, the UI looks a little different, but the options remain the same and the BIOS now has an option to disable CFG Lock without using the CFG unlock tool.
> 
> @jassingh9 Thanks so much for confirming CFG Lock can now be disabled. Would you mind confirming the model of your motherboard? [Is this the one](https://www.gigabyte.com/Motherboard/Z490-VISION-D-rev-1x#kf)? Also curious to hear which CPU you went with.

Yes i’ve got a Vision D paired with a 10900K

**Comment by bugsplat490** [comment]
Thanks all! (@jassingh9 @phao5814 @addisonduda ) Closing this issue!
