### ISSUE TITLE
Has anyone switched SMBIOS to iMac20,2 and gotten Sidecar working?

### ISSUE THREAD

**Issue by phao5814** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#49]
So it seems according to [this post](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-836) that setting SMBIOS to a Mac with a T2 chip means you cannot get Sidecar to work.

However, given the launch of the new iMacs for 2020, it seems that those with 10th Gen CPUs now have an SMBIOS that more closely resembles their hardware. For this repo, it seems more appropriate to change SMBIOS to **iMac20,2** ([since these iMacs come with 10 core 10th Gen CPUs](https://everymac.com/ultimate-mac-lookup/?search_keywords=iMac20,2)).

**However, my question is - has anyone tried iMac20,2 and also gotten Sidecar working? I'm asking because unfortunately the new iMacs do have T2 chips; however, I'm hoping that this doesn't stop Sidecar from working if I use iMac20,2 for my SMBIOS.** (I know Sidecar will work if you use iMac19,1 but it seems more appropriate to use iMac20,2 when using a 10-core 10th gen CPU. I'm asking because I'm trying to toss up between buying a 9th or a 10th get CPU)

Also, in the README, I spotted the following paragraph about no framebuffers being implemented yet.

> I have managed to enable the iGPU UHD630 but I couldn't get the HDMI-output working. I think this is, because there is no iMac out yet with a 10th Gen Intel with UHD630 so there are no framebuffers implemented yet. But I am no expert in this iGPU because I don't really need it since I have a Radeon VII.

Since new iMacs are out, I was wondering if this still holds true?

**Comment by a17uk** [comment]
I am using ASUS Prime Z490-A + RX570 4G + 10700k. Although we are using different MB,  but in terms of Sidecar, we should be the same. I am using SMBIOS iMac 19,2, without any frame-buffer setting. Sidecar is working but buggy, sometimes screen art, sometimes kernel panic. Have you tried some settings that work?

**Comment by rursache** [comment]
@a17uk you can get sidecar to work on iMac19,1 no issues whatsoever (using a cable). OP asked about iMac20,2 (and ,1 if you ask me)

**Comment by a17uk** [comment]
@rursache Is iMac 19,1 sidecar stable with 10th gen CPU? Are the settings the same as the one released? I tried switched from 19,2 to 19,1, but my USB map seems to always fail with iMac19,1, even I have changed the USB map kext. Sidecar did work on iMac19,1 but I don't know it is stable or not. Are there any differences between the wireless sidecar and with a cable?  Sorry I asked too much and they are not about iMac20,2. If iMac19,1 works perfect, there should be no need for considering 20,2. As far as I know, 9th gen and Z370 should be a stable match without too many issues. 10th gen is good enough so far in my opinion, despite my buggy sidecar :-p

**Comment by rursache** [comment]
my 10900k does well with iMac19,1 but it breaks DRM which is why i'm stuck with iMacPro1,1 and no sidecar. iMac20,2 would make DRM work as well as Sidecar (wired only), hence this thread. There is currently no way to use Sidecar wirelessly on hackintoshes.

**Comment by a17uk** [comment]
@rursache  Do you mean the wireless Sidecar is buggy or just cannot work with 19,2? My build can use sidecar wirelessly.

**Comment by rursache** [comment]
> @rursache Do you mean the wireless Sidecar is buggy or just cannot work with 19,2? My build can use sidecar wirelessly.

> Sidecar is working but buggy, sometimes screen art, sometimes kernel panic

Let's keep this thread free for SMBIOS iMac20,2 related stuff please

**Comment by jamesfawcett** [comment]
> @a17uk my 10900k does well with iMac19,1 but it breaks DRM which is why i'm stuck with iMacPro1,1 and no sidecar. iMac20,2 would make DRM work as well as Sidecar (wired only), hence this thread. There is currently no way to use Sidecar wirelessly **without weird glitches** on hackintoshes.

Have you seen this for 19,1
`Yes, through WEG (shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94 -> fake board id so DRM uses dGPU, thanks fewtarius )`

source: https://www.reddit.com/r/hackintosh/comments/dwbncg/sidecar_and_smbios_imac191_vs_imacpro11/

**Comment by rursache** [comment]
@jamesfawcett it doesn't work for Netflix and Apple TV app (and it breaks Intel QuickSync if i remember correctly) and i feel that iMacPro1,1 handles the CPU better and the whole system is more smooth on iMacPro1,1

**Comment by jamesfawcett** [comment]
Thanks @rursache - interested to try Big Sur on 20,2 when its officially released! 
I saw someone had released a kext to allow older models of Ipad to use sidecar (even my 4 year old iPad) on Reddit, I can't find it now but would love to try it out!

Sorry - off topic again :)

**Comment by addisonduda** [comment]
What have you all been using to generate iMac20,2 SMBIOS?

**Comment by rursache** [comment]
nothing, this is what the thread is about.

you can manually input the smbios id but it won’t boot.

**Comment by addisonduda** [comment]
Okay, my apologies - I misunderstood. I thought the original question was inferring it was available and was waiting for someone to test. However, I couldn't find software to generate, so I figured this was the case. Again apologies and thanks for the response anyway!

**Comment by SchmockLord** [comment]
Hey guys,

in the last couple of weeks, I have worked on a iMac20,2-based config. 

I have tested it on my AsRock Z490 Phantom, here are my results:
- works with Catalina without Fake CPU-ID, Big Sur Beta still requires Fake CPU-ID (config.plist>Kernel>Emulate)
- SideCar works with my iPad
- Apple TV works
- Amazon Prime in Safari doesn't work yet
- Netflix in Safari doesn't work yet, blacks out after a couple of seconds

The attached config is with
- iMac20,2
- without Fake CPU-ID, so for Catalina
- iGPU enabled 
- a 5700XT as dGPU

Can someone please test this config?

[EFI_10.15.6_iMac20,2_iGPU enabled+5700XT.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/5183196/EFI_10.15.6_iMac20.2_iGPU.enabled%2B5700XT.zip)

**Comment by rursache** [comment]
@SchmockLord will try to adapt to a Vision G board and give it a try

**Comment by rursache** [comment]
@SchmockLord here are my attempts with a Vision G board:

- The new iMac20,2 SMBIOS can be generated using OpenCore Configurator
- You must use the opencore files from the zip above (probably nighty builds) until 0.6.1 releases
- I managed to get the iMac20,2 SMBIOS boot, indeed TV app works, netflix and prime in safari does not, sidecar works great as well (wired). intel quicksync works (igpu hardware acceleration), video outputs to the 5700xt
- In order to get valid data in About this Mac (and prevent apps like Boom3D from crashing) you must only keep PlatformInfo/Generic in config.plist and change the UpdateSMBIOSMode key to "Create"
- VirtualSMC must be updated to display temperatures for 10900k (CPU i use). Worked OOB in iMacPro1,1

**Comment by SchmockLord** [comment]
Thanks for testing. Yeah. I have upgraded the OC Bootloader to OC 0.6.1 from 03.09. nightly build.

And I have updated to the newest kext available.

I just tried again, and it also works for Big Sur without the Fake CPUID.

**Comment by SchmockLord** [comment]
iMac20,2 and SideCar works now. Also AppleTV. Only thing that is not working yet is Amazon Prime and Netflix in Safari.
