### ISSUE TITLE
Can someone please test this version? 

### ISSUE THREAD

**Issue by SchmockLord** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#53]
Hey guys, 

I have been working on a new version of my Vision D config. But blindfolded, because I cannot test it for myself as I am working on my newest ITX-build: NCASE M1, i9-10900k, AsRock Z490 Phantom Gaming ITX/TB3, 5700XT.

The config is made for people with 5700XT and the internal graphics are setup for computing. So you should enable your "Internal Graphics" in BIOS. SMBIOS is iMacPro1,1. OpenCore is the nightly version from yesterday.

Would appreciate your help 👍 

[EFI_OC0.6.1_5700XT_iGPU enabled for computing_experimental.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/5073404/EFI_OC0.6.1_5700XT_iGPU.enabled.for.computing_experimental.zip)

**Comment by jassingh9** [comment]
Hey @SchmockLord congrats on the new build! I went ahead and tested this on my setup (Vision D, 10900K, 5700XT) and the updated EFI works great only issue I found was the iGPU is not showing in macOS even when setting the Internal Graphics option to enabled. I do not mind this as I have no use for the iGPU just thought i'd point it out. 
Thanks for all your help

**Comment by SchmockLord** [comment]
Great. All you said is explainable. 

The iGPU doesn't show up because it is setup as computing device only. And the boost for the 5700 XT comes from the SSDT-5700XT.aml.

**Comment by sebastienb** [comment]
Is it worth trying if i'm using imac19?

**Comment by SchmockLord** [comment]
Yes :)
