### ISSUE TITLE
Slow Download Speed

### ISSUE THREAD

**Issue by 0zguner** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#55]
Hey, thanks for the repo, My setup is GByte z490 vision G, 10700k and 5700 xt. I'm getting really low download speeds tested this on apfs and mac os journaled, Any ideas on that?

Two different results... Slow one is the native app, other is safari

![Screenshot 2020-08-15 at 13 57 36 2](https://user-images.githubusercontent.com/6003317/90321545-0523e080-df4b-11ea-9bfc-02632c8c4269.png)

**Comment by SchmockLord** [comment]
Maybe try a different Ethernet-driver. I don't have these issues. I am having a Fiber-Internet connection. And I am getting full speed: 1Gbit down/1Gbit up.

**Comment by 0zguner** [comment]
Different ethernet driver ? I think there only one option for i225v ?

**Comment by SchmockLord** [comment]
You didn't provide that info in the first place. Didn't know wether you use the 1Gb or the 2.5Gb.

Anyway. Just did a test. 

![Screenshot 2020-08-15 at 23 52 52](https://user-images.githubusercontent.com/19785918/90322264-a95d5580-df52-11ea-98b4-f4463d5e0b77.png)

**Comment by 0zguner** [comment]
Thanks, My issue with I225, its showing good result in browser but App store download is slower, and speedtest native app also is slower than browser. I'm getting expected result in browser as well.

**Comment by SchmockLord** [comment]
I just did the same test in the app:

![Screenshot 2020-08-16 at 00 02 25](https://user-images.githubusercontent.com/19785918/90322401-d0685700-df53-11ea-971e-c4c43bda5fc2.png)

Sorry for you, but this seems to not having anything to do with my config.

**Comment by 0zguner** [comment]
So I closed issue but forgot to share my solution. 
![Screenshot 2020-08-16 at 07 57 10](https://user-images.githubusercontent.com/6003317/90337261-2a8a0c00-df96-11ea-8b28-a3ec70af9d35.png)
