### ISSUE TITLE
Is it Safe to TurnOn FileVault

### ISSUE THREAD

**Issue by Nishant-Kathil** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#56]
Hi, Recently got my HackMac working. Is it safe to Turn On FileVault? Do we see any issues here?

**Comment by sebastienb** [comment]
I have it enabled and no issues on my end

**Comment by Nishant-Kathil** [comment]
FileVault works like Magic
