### ISSUE TITLE
Motherboard HDMI is not working on IMAC 19 config on version 3.1 -- Solved

### ISSUE THREAD

**Issue by sebastienb** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#57]
Hi Chris,
I just updated my EFI to use your version 3.1 with the config_iMac19,1_Enable iGPU_HDMI-output via iGPU.plist but the HDMI out on MB is not working. I double checked that the iGPUis enabled in my Bios.

**Comment by SchmockLord** [comment]
Hey @sebastienb,

can you please try it with the newest EFI again? Haven't made a special release for it yet, just committed to the repo a couple of seconds ago.

Best,
Chris

**Comment by sebastienb** [comment]
Okay I will try it and get back to you. Thanks

**Comment by sebastienb** [comment]
It worked! Also just found a fix my final cut issue. I'll add details to my open issue for
Final cut.

**Comment by sebastienb** [comment]
I can't find my final cut issue.

To get final cut to work I had to set the igpu as the main video device in the bios. Now I need to check if I can boot with no display connected to it.

**Comment by Nishant-Kathil** [comment]
@sebastienb - were you able to get the Display device working? I am using the latest published EFI but couldn't get my Monitor working through Motherboard HDMI?

**Comment by sebastienb** [comment]
It works for me, make sure you use the imac19 confit file and make sure the igpu is enabled in your bios.

**Comment by Nishant-Kathil** [comment]
I renamed config_iMac19,1_Enable iGPU_HDMI-output via iGPU.plist to config.plist and changed the serials. Used the EFI folder as it is.

Updated BIOS to make Internal Graphics Enabled (Changed setting from Auto-->Enables)
Updated BIOS to make the default display as iGFX

@sebastienb - anything I am missing or some Post Install setting?

**Comment by sebastienb** [comment]
That's all I did. The first time I tried it it didn;t work and took a while to boot. I think I reset my vram before next try.

**Comment by Nishant-Kathil** [comment]
I think there is a difference in EFI 3.1 release version download and full package download. I can see SMBus Support set to True

			<dict>
				<key>Comment</key>
				<string>Improves SMBus Support</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-SBUS-MCHC.aml</string>
			</dict>

and also alot of Framebuffer settings. Let me try this and post an update

**Comment by Nishant-Kathil** [comment]
It's working now and I can get a display out of HDMI as well...Great

Few Problems I am still running into -

1. If I change the BIOS settings make the default display as iGFX
   a. Sometimes I am getting the Start Image load failed error while loading MacOS
   b. After reboot, I need to plug-in the HDMI cable again. If the cable is already plugged in Motherboard HDMI port it doest work.

I changed the default display back to PCI Card and don't run into that error anymore (Start Image). To get the iGPU working I need to replug my HDMI cables.

Hopefully with future fixes this works out smoothly

**Comment by sebastienb** [comment]
> It's working now and I can get a display out of HDMI as well...Great
> 
> Few Problems I am still running into -
> 
> 1. If I change the BIOS settings make the default display as iGFX
>    a. Sometimes I am getting the Start Image load failed error while loading MacOS.
>    b. After reboot, I need to plug-in the HDMI cable again. If the cable is already plugged in Motherboard HDMI port it doesn't work.
> 
> I changed the default display back to PCI Card and don't run into that error anymore (Start Image). To get the iGPU working I need to replug my HDMI cables after every boot
> 
> Hopefully, with future fixes, this works out smoothly

If you don't have the iGPU set as the main video device you might not be able to open final cut. I had a boot issue on my first boot but did the nvram reset and haven't had this issue since.
