### ISSUE TITLE
What is the purpose of the additional Audio kexts in the configuration?

### ISSUE THREAD

**Issue by phao5814** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#59]
For Audio, what is the purpose of the additional kexts in your configuration?

> Audio: Realtek ALC1220-VB (AppleALC.kext, layout-id=7, device-id=0xA170, FakeID.kext, FakePCIID_Intel_HDMI_Audio.kext)

I'm just trying to understand everything better because according to the [documentation](https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#making-layout-id-more-permanent) for OpenCore, if we find a layout-id that works with our motherboard, that should be it. I can't find anything about installing more audio kexts in the OpenCore docs to make audio work.

**Comment by SchmockLord** [comment]
You can try your best but for me just the ALCID=7 doesn't work. Always if I left out any of the other files you mentioned, my Audio stopps working. The device is detected but no sound.
