### ISSUE TITLE
Legacy OS support - High Sierra

### ISSUE THREAD

**Issue by ManMantissa** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#6]
First up - thanks so much for posting this Chris - we appreciate your time and expertise to get everything working on the new chipset.
Q: Do you see any issues with running older versions of OSX on this build - specifically High Sierra? 
I'm a little attached to High Sierra, only because if I update I'll lose the use of some older AU plugins that are no longer supported or updated for Mojave >> and Catalina just looks like a Pandora's Box for audio issues, so I'm not going there.
Cheers, Cam.

**Comment by SchmockLord** [comment]
Hi, you are welcome.

I haven't tried High Sierra because I don't need it. I am not sure if it is running because of the Fake-CPU-ID and that the CPU is a 10th Gen. I think you have to try that by yourself.
