### ISSUE TITLE
Instant wakeup with my custom SSDT-UIAC.aml

### ISSUE THREAD

**Issue by jamesfawcett** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#61]
Hello, after weeks of trying to work out why my machine keeps waking up instantly from sleep with error `processWakeReason Wake reason: Host (0x01)` , I've finally figured out the cause is the USB SSDT's, but not been able to fix it yet.

If I use one of your custom SSDT-UIAC files in your repo, my machine will sleep correctly. I am just wondering if I am missing a step, or if you have any ideas?

To create my own SSDT's, I deleted HS14 (bluetooth?) and all the ports marked internal. I generated a custom SSDT-UIAC.aml and SSDT-EC-USBX.aml using Hackintool and your guide in the README.

![image](https://user-images.githubusercontent.com/5245272/91211691-174e0d80-e707-11ea-863b-fb9d5dea513f.png)

Sorry, I know this is out of scope as I have different hardware to you, but it would be great if you have any clues for me to solve it.

Thanks
James 

[SSDT files.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/5125561/SSDT.files.zip)

Edit - just labeled my ports in the SSDT and removed the USB hub entries.

**Comment by SchmockLord** [comment]
Why do you want to create your own SSDT for USB? I mean, I have already put in 3 variations, and in the 3rd one, all ports are working.

**Comment by jamesfawcett** [comment]
Thanks it's because my board is different unfortunately, this is the motherboard I am using: https://www.gigabyte.com/Motherboard/Z490-AORUS-PRO-AX-rev-1x

I will try the SSDT-UIAC-USB-Z490-VISIOND-ALTERNATIVE-3.aml

**Comment by jamesfawcett** [comment]
Thanks it's because my board is different unfortunately, this is the motherboard I am using: https://www.gigabyte.com/Motherboard/Z490-AORUS-PRO-AX-rev-1x

SSDT-UIAC-USB-Z490-VISIOND-ALTERNATIVE-**1**.aml = sleep works 👍 , ports incorrect  👎 :(

SSDT-UIAC-USB-Z490-VISIOND-ALTERNATIVE-**3**.aml = sleep not working 👎 , ports similar but not correct `AppleACPIPlatformPower Wake reason: XDCI USBW PEG1 PEG2 RP04 (User) Wake reason: Host (0x01)`

My own config generated = sleep not working 👎  ports correct `AppleACPIPlatformPower Wake reason: XDCI USBW PEG1 PEG2 RP04 (User) Wake reason: Host (0x01)`

I will test SSDT-UIAC-USB-Z490-VISIOND-ALTERNATIVE-**2**.aml now :)

**Comment by jamesfawcett** [comment]
Just doing some notes:
Differences - I am using HS08, HS10. 
I have SS08, SS09, SS10
yours uses HS11
+ Added in XHC5 section

....so what I found was, exporting my ports from Hackintool would not work. Sleep would not enable.

I copied my ports in my aml file into your **SSDT-UIAC-USB-Z490-VISIOND-ALTERNATIVE-1.aml**. When exporting from Hackintool, this bit was missing which is included in yours:

![image](https://user-images.githubusercontent.com/5245272/91234310-df58c180-e72a-11ea-8af1-0b33894587dc.png)

I increased my "ports" to (0x22). I now have that in my compiled SSDT-UIAC.aml, I have correct ports and sleep 👍 

I think somewhere I have an error on my .aml file, because the "comment" column in Hackintool is missing my comments and I see this: 
![image](https://user-images.githubusercontent.com/5245272/91234409-13cc7d80-e72b-11ea-8c7d-4a4e5353e7a1.png)

Here is my SSDT so far, this works for sleep and all ports on Aorus Z490 Pro Ax

[SSDT-UIAC.aml.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/files/5126603/SSDT-UIAC.aml.zip)

Tomorrow I will try fix the comment error in Hackintool.

**Comment by jamesfawcett** [comment]
Hi sorry to trouble you again.

I spotted two issues, the first one, is an issue with Hackintool import/export. When importing an existing config to edit, it groups the changes as a separate block of ports. I will report this issue with them. When the aml is read, only the second group of ports become active: 

![image](https://user-images.githubusercontent.com/5245272/91604244-39919680-e966-11ea-8547-e45f6106adf0.png)


My sleep issue is due to HS13 on my board. When I have HS13 enabled, I have bluetooth, but the machine instantly wakes up from sleep. When disabled, no bluetooth, but sleep works. I have tried all the different options (Internal, USB2, USB3 etc) for HS13.

Please let me know if you have any other ideas. It seems unresolved wherever I look for answers: https://www.reddit.com/r/hackintosh/comments/doewpu/immediate_wake_from_sleep_when_internal_usb/

thanks
James

**Comment by jamesfawcett** [comment]
I'm still trying to debug this one. Please could someone that is using an internal usb header for their bluetooth please compare your port to mine in IORegistry Editor.

My HS13 is my bluetooth, but also it seems to be a USB Hub too: 

![Screenshot 2020-09-02 at 18 41 14](https://user-images.githubusercontent.com/5245272/92020638-5ce68800-ed50-11ea-84b3-0533793b4cc3.png)

If I delete HS13 completely sleep works, but no bluetooth. If I enable HS13 and have it set to internal or any other setting in Hackintool, no sleep.

**Comment by jamesfawcett** [comment]
Passed my question over to TonyMac forums.... wish me luck 
https://www.tonymacx86.com/threads/fenvi-t919-and-corsair-icue-usb-share-same-usb-header.303286/
