### ISSUE TITLE
config_iMac20,2_iGPU+5700XT.plist bluethooth can't turn on/off

### ISSUE THREAD

**Issue by dhlsam** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#65]
Hi, I updated imac.19,1 to OC 0.6.1 (nightly 8th Sep 2020) + iMac20,2 config EFI files,
everything works fine except bluethooth,i am using MQUPIN fenvi T919 Wireless/Bluetooth Card
but bluethooth doesn't work after using imac20,2 config. anyone got this problem?
![Screen Shot 2020-09-11 at 1 09 55 AM](https://user-images.githubusercontent.com/390439/92769940-06222380-f3cc-11ea-9bc8-4c867f66a67a.png)
![Screen Shot 2020-09-11 at 1 09 43 AM](https://user-images.githubusercontent.com/390439/92769951-08847d80-f3cc-11ea-9e2a-b6a11cfe6788.png)
![Screen Shot 2020-09-11 at 1 06 37 AM](https://user-images.githubusercontent.com/390439/92769958-0a4e4100-f3cc-11ea-91e7-e1119c38a55a.png)

**Comment by jeffreychucASAPP** [comment]
I have the same issue, I'm curious why @SchmockLord didn't see this when updating to 20,2

**Comment by dhlsam** [comment]
USBInjectAll version 0.7.6 that adds compatibility with iMac20,1 and iMac20,2

**Comment by SchmockLord** [comment]
And where can you download the 0.7.6? I only find 0.7.5.

**Comment by dhlsam** [comment]
> And where can you download the 0.7.6? I can only find 0.7.5.

https://github.com/CaseySJ/OS-X-USB-Inject-All/releases/tag/0.7.6

**Comment by SchmockLord** [comment]
Thanks @dhlsam. Updated my config with the 0.7.6.
