### ISSUE TITLE
Can someone share the process to generate smbios for iMac 20,2

### ISSUE THREAD

**Issue by Nishant-Kathil** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#66]
Can someone share the process to generate SMBIOS for iMac 20,2?

I can't find this in Clover Configurator. I was able to get it generated from OpenCore Configurator but ROM Value is empty and Spoof Vendor is False

**Comment by bdunncompany** [comment]
I have the same issue. Can't find the answer anywhere.

**Comment by Nishant-Kathil** [comment]
I finally got it working by generating SMBIOS through OpenCore Configurator for iMac 20,2.

**Comment by Nishant-Kathil** [comment]
Closing this issue
