### ISSUE TITLE
Minimum, installation-safe EFI

### ISSUE THREAD

**Issue by eos-alchemist** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#7]
`So, first: Thank You so much for posting pioneer-character work, your time and all enthusiasm to get Z490 configuration working.`

I've build with:
- Gigabyte Z490 **Vision-D**
- i9 **10900K**
- Radeion 5700XT
- BIOS version **F3**, set-up like you describes here
- _clean_ Catalina install + **EFI** from your repository

I've try:
- boot + select Installation from **USB**
- installation show **logo** + progress bar
- after maybe **20% - dark** ...

Could you please, publish something like `simple, instalation-safe EFI (minimum modules + settings, only needed things)` ? _Fot trouhleshooting, debug and enhancing your original set-up?_

Thank you very much for your help ...

**Comment by SchmockLord** [comment]
Add bootarg -v and share the screen before it gets black.

**Comment by MidnightDiner** [comment]
Hey Eos-alchemist. I'm using the Radeon 5700XT. Because it used Navi you need to add agdpmod=pikera to bootargs. 

SmockLord, thank you so much for posting this! I was worried that the Z490 chipset was going to be problematic. It was a great relief that you shared all this info! Thanks!

**Comment by MidnightDiner** [comment]
> `So, first: Thank You so much for posting pioneer-character work, your time and all enthusiasm to get Z490 configuration working.`
> 
> I've build with:
> 
> * Gigabyte Z490 **Vision-D**
> * i9 **10900K**
> * Radeion 5700XT
> * BIOS version **F3**, set-up like you describes here
> * _clean_ Catalina install + **EFI** from your repository
> 
> I've try:
> 
> * boot + select Installation from **USB**
> * installation show **logo** + progress bar
> * after maybe **20% - dark** ...
> 
> Could you please, publish something like `simple, instalation-safe EFI (minimum modules + settings, only needed things)` ? _Fot trouhleshooting, debug and enhancing your original set-up?_
> 
> Thank you very much for your help ...

Also, you should remove the RadeonBoost kext from the kexts folder and the config.plist. It doesn't support for Navi bed 5700XT and also has issues with Catalina 10.5.5

**Comment by eos-alchemist** [comment]
Thank you all ... Now I'm fix it for installation by removing 5700XT and use internal Intel 630. Next round be try all this advises.

**Comment by 99electronic** [comment]
> Hey Eos-alchemist. I'm using the Radeon 5700XT. Because it used Navi you need to add agdpmod=pikera to bootargs.
> 
> SmockLord, thank you so much for posting this! I was worried that the Z490 chipset was going to be problematic. It was a great relief that you shared all this info! Thanks!

Hey, I can run RX580 no problem, but I can't boot into 5700XT. It does load apple logo but when it needs to switch to login screen it is black. Could you possibly share your EFI ? Are you using vision D board?  I always used clover as bootloader and do not really know OC. How would I add the argument you are talking about? All help would be appreciated.

**Comment by 99electronic** [comment]
> Hey Eos-alchemist. I'm using the Radeon 5700XT. Because it used Navi you need to add agdpmod=pikera to bootargs.
> 
> SmockLord, thank you so much for posting this! I was worried that the Z490 chipset was going to be problematic. It was a great relief that you shared all this info! Thanks!

Hey, I can run RX580 no problem, but I can't boot into 5700XT. It does load apple logo but when it needs to switch to login screen it is black. Could you possibly share your EFI ? Are you using vision D board? I always used clover as bootloader and do not really know OC. How would I add the argument you are talking about? All help would be appreciated.

**Comment by 99electronic** [comment]
I made it work by updating to 10.15.5, everything works from now. The 2 DP displays too (2x4k@60Hz) even thunderbolt display works now.

**Comment by SchmockLord** [comment]
Minimum-Kexts for booting?

Lilu.kext, Whatevergreen.kext and USBInjectAll.kext. Nothing more. And if you have no Wifi/BT-card that is natively supported you should also enable IntelMausiEthernet.kext so you have Ethernet (only 1Gbit port is working then).

**Comment by RedEars** [comment]
> > `So, first: Thank You so much for posting pioneer-character work, your time and all enthusiasm to get Z490 configuration working.`
> > I've build with:
> > 
> > * Gigabyte Z490 **Vision-D**
> > * i9 **10900K**
> > * Radeion 5700XT
> > * BIOS version **F3**, set-up like you describes here
> > * _clean_ Catalina install + **EFI** from your repository
> > 
> > I've try:
> > 
> > * boot + select Installation from **USB**
> > * installation show **logo** + progress bar
> > * after maybe **20% - dark** ...
> > 
> > Could you please, publish something like `simple, instalation-safe EFI (minimum modules + settings, only needed things)` ? _Fot trouhleshooting, debug and enhancing your original set-up?_
> > Thank you very much for your help ...
> 
> Also, you should remove the RadeonBoost kext from the kexts folder and the config.plist. It doesn't support for Navi bed 5700XT and also has issues with Catalina 10.5.5

Thanks! That fixed the reboot-loop I had with the 5700XT

**Comment by SchmockLord** [comment]
I am just guessing: Have you disabled your iGPU in BIOS? Not Auto, disable.

And are you using my config.plist with SMBIOS=iMacPro1,1 or iMac19,1?

Try disabling the iGPU in BIOS and then use the config.plist with SMBIOS=iMacPro1,1

**Comment by RedEars** [comment]
Yes, iGPU is disabled and I am using iMacPro1,1. 
Going to buy a DP cable later just to make sure it’s not the HDMI cable I use.

**Comment by SchmockLord** [comment]
Ok, when you say flickering then I think a different DP-cable will solve this. And try a short one. I have a 49" screen with 5120x1440 at 120hz. And I tried 5 cables, only 1 worked without any issues. At this resolution and this framerate, the cable becomes critical if it is more than 3m long. Sometimes already 1.5m is an issue with some cables. And normally the one that the monitor is shipped with, is working.

**Comment by RedEars** [comment]
Seems like its working now with the new cable!
By the way, thanks for this repo - it was very helpful to create hackintosh!
