### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by waelalmeiry** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#70]
I would like to express my deep appreciation for your work. Just nowadays I booted my hackintosh using your efi folder.![image](https://user-images.githubusercontent.com/58885956/93925714-326c6700-fd1f-11ea-8e00-c1595c9a050f.jpeg)

**Comment by waelalmeiry** [comment]
Same System except that I have dual boot windows 10. After I updated drivers from Gigabyte website Hackintosh cracked. I tried it reproduce the operation but the installer can't see the nvme or hdd on the motherboard.
Why?

**Comment by SchmockLord** [comment]
Thanks for your appreciation. Have you solved the issue? Seems more like a non Hackintosh issue.

**Comment by waelalmeiry** [comment]
Yes.
Thanks

**Comment by waelalmeiry** [comment]
Yes
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
