### ISSUE TITLE
NVMe not seen after I already succeeded in installing Mac, MY EFI is the one provided by SchmockLord using iMacPro 1,1

### ISSUE THREAD

**Issue by waelalmeiry** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#73]
1- Hardware: GA Z490 Vision D, i7 10700K, Corsair 32 Vengeance LPX 3600, 2x WD SN750 NVMe, Sapphire RX5700XT Nitro plus.
2- I installed Bis Sur and windows 10 the updated windows then system crashed.
3- Installed Catalina then W10 then updated drivers of MoBo then system crashed.
4- THE PROBLEM NOW BOTH MACOS INSTALLER CAN NOT SEE MY NVMe.
PLEASE HELP

**Comment by addisonduda** [comment]
Did you remove the macOS NVMe before installing Windows 10? Windows 10 has been reported to have installation issues... Where, even though you specified which NVMe to install the software on, Windows 10 can write onto a different drive. This is not to say you selected the wrong drive, but that Windows installer has issues. I can imagine if this was the case, some of your hard work may have been overwritten and thats why it can't read your drive anymore.

**Comment by addisonduda** [comment]
So to solve this... it might be best to completely whipe both NVMe drives. Add one NVMe to the motherboard and install macOS with your modified EFI (from Chris). Remove this macOS NVMe drive and install the other empty NVMe drive. Install Windows 10 on the empty NVMe. Finally, add the macOS NVMe back to the board and you should be all set. Also, make sure you don't have any other drives  (HDD, SSD) connected during the OS installation process.

**Comment by waelalmeiry** [comment]
Thanks Sir


Dr. Wael Hamed ALMEIRY
MD Neurosurgery
________________________________

**Comment by waelalmeiry** [comment]
Dear friend 
I tried what have you supposed but not working

**Comment by addisonduda** [comment]
Do the NVMe drivers still show up in BIOS?

**Comment by waelalmeiry** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by waelalmeiry** [comment]
Now NO SIGNAL TO MONITOR HDMI

**Comment by waelalmeiry** [comment]
Help now NO signal to display
Both Sapphire card and iGPU
What is cause?

**Comment by waelalmeiry** [comment]
It was complicated. No signal at HDMI. Step wise I stepped everyone thing but mobo,cpu, cooler, used my TV as monitor and changed cable, removed both nvmes and hdds then installed F6 bios then started step by step as you recommended and now it is working and it is time to finish hardware job. Very[important to install using Single NVMe at time]

**Comment by waelalmeiry** [comment]
Dear Chris
Is this config.plist cotains USB mapping or shall I do it? Because system information said No thunderbolt hardware.
```suggestion

```
![Uploading 94958238...]

**Comment by SchmockLord** [comment]
This is normal and you can use my USB port mapping.
