### ISSUE TITLE
Booting USB reboots back to BIOS

### ISSUE THREAD

**Issue by prozacstudio** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#76]
Hi again

I'm having trouble, get exact same hardware as yours, created a Catalina installer but after it's set up for boot drive after a short moment it reverts me to bios... Open Core troubleshooting says it may have something to not having proper OC folder structure but I copied all the files exactly to the EFI partiotion of the USB drive. Tried different flash drives and usb ports but it's still the same... https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#booting-opencore-reboots-to-bios 
Any clue what it can be? Thank you in advance!

**Comment by g3d** [comment]
I had a similar issue, please ensure you write EFI folder into EFI partition, so in the partition, you should have one folder (EFI) instead of 2 (BOOT & OPENCORE)

**Comment by prozacstudio** [comment]
@g3d Yes, thank you. I figured it out a bit ago. After few hours of digging I found a post on reddit about it... little details. Thanks again
