### ISSUE TITLE
Rename PEGP to EGP0 (Graphics) I think has the wrong table

### ISSUE THREAD

**Issue by zb1ackcat** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#77]
I could not get PEGP to update to EGP0 and I noticed your table was identical to the replace value.

I updated it to 44534454 and now it works for me in IOREG

Was going to go a pull request on this, but I have done to many tweaks on my fork.

**Comment by SchmockLord** [comment]
Thanks for your info.

Can you share more details what you have added in the ACPI section?

**Comment by SchmockLord** [comment]
Just fixed that. But I have disabled this patch as a default.
