### ISSUE TITLE
Fan and temperature read/control

### ISSUE THREAD

**Issue by prozacstudio** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#78]
Hi. Do you use any software for checkin temps on cpu/gpu/drives? I tried iStats but is show only drives temp and nothing more. Other then that build is working perfectly fine! Thanks a lot for putting it together.

**Comment by SchmockLord** [comment]
I think the issue is simply, that iStat is not supporting iMac20,2 yet. Because the HWMonitor.app shows all voltage and temperatures.

**Comment by addisonduda** [comment]
iStats just updated. I can see temps for CPU with iMac20,2
