### ISSUE TITLE
Mobile vs Desktop iGPU

### ISSUE THREAD

**Issue by addisonduda** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#79]
Hey Chris. Is there a reason you're using the mobile iGPU identifier instead of the desktop iGPU in Device Properties/Add/PciRoot(0x0)/Pci(0x2,0x0)/device-id? The last few EFIs have been using <92BE0000> for mobile instead of <923E0000> for desktop. Thanks!

**Comment by SchmockLord** [comment]
Thanks for this hint. Will check it. Didn't change that on purpose.
