### ISSUE TITLE
No bluetooth hardware

### ISSUE THREAD

**Issue by bdunncompany** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#80]
I have no bluetooth hardware available. Everything else is working fine. I have the MQUPIN fenvi T919 card with the chip BCM94360CD.

I have added "uia_exclude=HS14" to the end of the boot-args in my EFI/EFI/config.plist file as such: "shikigva=80 keepsyms=1 debug=0x100 agdpmod=pikera uia_exclude=HS14" and I located that under /Root/NVRAM/Add/7C....GUID...../boot-args.

Note that Bluetooth Explorer doesn't come with Additional Tools for Xcode 12 so I had to get the latest Xcode 11 Additional Tools. When I run that it tells me that there is no Bluetooth hardware.

I believe I have followed the directions and this is a pretty generic system with little to zero customizations outside of this Github repo.

Thanks for any suggestions.

**Comment by jamesfawcett** [comment]
Is your usb header jumper wire connected properly to the motherboard from the Fenvi? Which header did you connect it to, and is it 180degrees out?

**Comment by SchmockLord** [comment]
First and most important question: Do you use the same board? 

If so, my USB configurations already disable HS14 to disable the internal Intel Bluetooth. Then you should plugin the USB 2.0 of the Fenvi T919 to the HS11 ports shown on these images here: 
https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/blob/master/USB-Port-Configuration.md

**Comment by bdunncompany** [comment]
I am so sorry. I failed to read the directions with the Fenvi and failed to notice the included cable. I am up and working fine along with feeling very stupid. Thanks for your help!
