### ISSUE TITLE
iMac20,2 sound device device-id

### ISSUE THREAD

**Issue by addisonduda** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#82]
Both iMac20,2 configs still have PciRoot(0x0)/Pci(0x1F,0x3). iMac20,2_iGPU with display output with 5700XT works well without it. However, my headphones are not recognized at either front or rear IO.

**Comment by jamesfawcett** [comment]
I had the same issue, I've copied the rest of the updates to my EFI, but for sound I've added back in FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext. I didn't like the GUI bootloader screen or sound drivers so I removed those, I much prefer the simple text version. 

I also noticed two more errors with the iMac20,2 configs: 

`<key>LegacyCommpage</key>
			<false/>`
(in quirks)

and...

`<key>MemoryFormFactor</key>
			<string>Auto</string>`
(in PlatformInfo)

...both cause errors with OpenCore. I had to remove those parts. 

The error began with `OCS: No schema for LegacyCommpage at...`

**Comment by dhlsam** [comment]
I had the same issue,headphones are not recognized

**Comment by SchmockLord** [comment]
Hey @addisonduda. Can you please test, if the onboard sound works with the newest config? 

I just removed the FakeID Kext files because I heard that they are not required since OC 0.6.1. But I left all the device-ids in the device properties. 

E.g. does your 2.5GBit Ethernet still work?

**Comment by addisonduda** [comment]
Hey @SchmockLord. 2.5 Gbit Ethernet is not working and is not recognized in Network settings with the config posted ~30 minutes ago. Headphones are also not recognized. However, 1 Gbit Ethernet is recognized in the Network settings.

The only changes I made to the config were to add my PlatformInfo(s) and include uia_exclude=HS14 to bootlegs

**Comment by SchmockLord** [comment]
Thanks @addisonduda. I think that this is because the FakePCIID_Intel_I225-V.kext might still be required. Can you test to put this into your config again, but without FakePCIID.kext?

**Comment by addisonduda** [comment]
Still not working with this added in. :/ @SchmockLord 

I have also been seeing _OCS: No Schema for MemoryFormFactor..._ in all GUI bootloaders (as @jamesfawcett mentioned) since the EFI last night.

**Comment by SchmockLord** [comment]
The MemoryFormFactor message is an easy one. The OC developers (no critique, god bless them) did kind of a last-minute rename on this setting. It was named MemoryFormFactor in a nightly 0.6.2 and then it has been renamed to SystemMemoryStatus in the final 0.6.2.

But if you still get this message, you should do an NVRAM reset. In my newest EFI it has the correct name SystemMemoryStatus.

**Comment by addisonduda** [comment]
2.5 Gbit now shows and works, but still no recognition of headphones on front or rear IO. I'm gonna add FakePCIID_Intel_HDMI_Audio.kext and check back

**Comment by SchmockLord** [comment]
Yeah, I see. It is in 2 the 3 configs. Will fix that now.

**Comment by addisonduda** [comment]
Yeah, audio IO works great now with all FakePCIID... kexts, just as @jamesfawcett found. I left in the device-ids.

I can't tell if I have the _OCS: No schema for LegacyCommpage at..._ as he also mentioned. With the resolution being messed up, it could be hidden.

**Comment by SchmockLord** [comment]
The issues should be fixed now. Thanks for pointing that out!
