### ISSUE TITLE
Radeon VII changes?

### ISSUE THREAD

**Issue by hwhh** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#84]
Hi, 

Thanks for the awesome repo! I was wondering what if any changes would need to be made when using a Radeon VII? I noticed the `DAGPM` kext is included and guessed this should be removed but I was also wondering if it is advisable to remove the `agdpmod=pikera` boot argument, as it only mentions adding this for Navi 10 Series cards on [dortania GPU buyers guide](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#navi-10-series)

**Comment by SchmockLord** [comment]
disable DAGPM.kext and SSDT-5700XT.aml. Instead I would use radeonboost.kext for the Radeon VII. Agdpmod=pikera can stay.

**Comment by hwhh** [comment]
Great, thanks again!
