### ISSUE TITLE
Audio fix front panel

### ISSUE THREAD

**Issue by lightpower888** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#86]
Hello my friend! I tried the last efi that you have made and everything works perfectly except the headphones on the front panel of the case.

My system is:
Gigabyte Vision D Z490 (with bios ver F6)
CPU i9-10850K
GPU IGPU UHD630
With SMBIOS iMac20,2

Can you help me solve this problem?

**Comment by SchmockLord** [comment]
Does the onboard sound work from the backpanel ports?

**Comment by lightpower888** [comment]
Yes, the sound works on the rear doors, it does not work on the front

**Comment by SchmockLord** [comment]
Then I would say, you should check how you have connected the front panel Audio connector.

**Comment by lightpower888** [comment]
when I set it to alcid = 28 then the front panel of the audio also works

**Comment by SchmockLord** [comment]
Thanks for the hint. Today (Working from home) I noticed, that the front Audio of my NCASE M1 only plays sound, but the microphone doesn't work and sounds weird. So I will try it with your alcid again.

**Comment by g3d** [comment]
Yes, I have the same problem, mic doesn't work, but at least audio works.

**Comment by lightpower888** [comment]
Good morning to everyone! For
Fractal Design Define 7 The sound on the front panel does not work unfortunately.

**Comment by SchmockLord** [comment]
@lightpower888 I thought it is working with 28? What does the case have to do with this.

I have tested 28 on my AsRock Phantom Z490. Now I have Sound and Microphone working. Front and Back panel.

But if I start Windows via OpenCore, the Mic is not working. Only Sound.

So 28 seems to be better but not is still not perfect for people who start Windows via OpenCore.

**Comment by SchmockLord** [comment]
Fixed with the current release. Please test it.

**Comment by lightpower888** [comment]
I tried it and it works perfectly. The only problem is: When I connect headphones or microphone etc the sound does not change automatically I have to change it manually from the audio panel.
