### ISSUE TITLE
Graphics Gard

### ISSUE THREAD

**Issue by Jimbojingle** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#9]
Which make of Radeon VII did you use in your build?

**Comment by neilpanchal** [comment]
If you are looking to buy one, the best bang for buck is actually the AMD Radeon RX 5700 XT. Around $400 and it should work without any issues.

**Comment by Scope666** [comment]
I got this one as a secondary card since I do all my gaming in Windows with a RTX 2080 Ti (disabled on Mac side)

https://www.asrock.com/Graphics-Card/AMD/Phantom%20Gaming%20Radeon%20RX560%204G/

$109 and doesn't require any PCI-E power cables.  Running two monitors,  1440p / 144Hz and 1080p / 60Hz with no issues.

**Comment by SchmockLord** [comment]
In my system I have a Asrock Phantom Gaming X Radeon VII: 
https://www.asrock.com/Graphics-Card/AMD/Phantom%20Gaming%20X%20Radeon%20VII%2016G/index.de.asp

But I would choose 5700XT at the moment.

**Comment by Jimbojingle** [comment]
Is a Radeon 5700 XT any good for Gaming and VR or is a Radeon V II better?

**Comment by Jimbojingle** [comment]
> I got this one as a secondary card since I do all my gaming in Windows with a RTX 2080 Ti (disabled on Mac side)
> 
> https://www.asrock.com/Graphics-Card/AMD/Phantom%20Gaming%20Radeon%20RX560%204G/
> 
> $109 and doesn't require any PCI-E power cables. Running two monitors, 1440p / 144Hz and 1080p / 60Hz with no issues.

How do you run two Graphics Cards and disable the Nvidia one on macOS?

**Comment by Scope666** [comment]
Taken from here:

https://dortania.github.io/OpenCore-Desktop-Guide/extras/spoof.html

![image](https://user-images.githubusercontent.com/31927547/83696267-07bc9e00-a5ca-11ea-915b-a0db774ea935.png)

**Comment by Jimbojingle** [comment]
So, any recommendations to help me make my mind up on which Graphics Card?

Radeon 5700 XT any good for Gaming and VR or Radeon VII? Or I already have a Gigabyte GTX 1070Ti which I could use for Windows Gaming but disable in macOS.

Also does the make matter from a compatibility point of view. I have read that Sapphire cards are the most compatible.

**Comment by neilpanchal** [comment]
@Jimbojingle I highly recommend the Navi architecture Radeon RX 5700 XT. Apple's W5700X[1] is essentially the same card with additional 8GB VRAM. AMD also sells W5700XT but unless you need professional support for the card, 5700 XT is identical to both in most aspects.

[1] https://www.apple.com/shop/product/MW662AM/A/radeon-pro-w5700x-mpx-module

**Comment by Jimbojingle** [comment]
Thanks,

I will go for that option. 

Does it matter which make of card? As I mentioned previously, I have read that Sapphire cards are the most compatible.

**Comment by SchmockLord** [comment]
If you already have a 1070 Ti for gaming, I would go for the 5700XT (or maybe even slower). Depends on what you want to do on MacOS but the 5700XT e.g. for video encoding is even faster than the Radeon VII.

**Comment by neilpanchal** [comment]
@Jimbojingle I don't think it will matter, but I agree with you, Sapphire seems to have the best reputation to be hassle-free and Apple officially recommends Sapphire brand.

**Comment by Jimbojingle** [comment]
Thanks,

Just to be sure, I was looking at the 'Sapphire RX 5700 XT NITRO+ Special Ed. 8GB GDDR6 PCIe 4.0’. There are several variants of this card but this seems to be the best!
