### ISSUE TITLE
Mac OS 11 lässt sich nicht installieren

### ISSUE THREAD

**Issue by torben1404** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#90]
Hi Chris, ich bin's nochmal.

Ich bin leider nicht in der Lage die MACOS 11 Beta zu installieren. Spätestens nach dem ersten Ladescreen schmiert das ganze System ab.

Wäre super, wenn du weiterhelfen könntest!

**Comment by SchmockLord** [comment]
Ne, kann ich auf der Basis nicht. Ich hab keine Ahnung welche Hardware du benutzt, was du im BIOS eingestellt hast und welchen Installer du benutzt.

**Comment by torben1404** [comment]
Ich nutze:

CPU: i9-10900k
GPU: RX 5700 XT Sapphire Nitro +
Mainboard: Z490 Vision D
BIOS und Efi sind wie aus deinem Video, bzw. die letzte Version deiner hochgeladenen.

**Comment by SchmockLord** [comment]
Wie weit kommst du denn genau? Kommt der Ladebalken oder schmiert er genau da ab?

Kannst du in den Bootargumenten mal -v ergänzen und dann einen Screenshot machen, wo er hängen bleibt?

**Comment by torben1404** [comment]
Der Ladebalken kommt und schmiert bei 3/4 ab. Ich kann später das Bootargument ändern.
Ich bin aber für den Moment wieder zurück auf Catalina. Wenn die Tage offiziell MacOS 11 kommt werde ich es testen. Danke dir bis dahin.
