### ISSUE TITLE
Big Sur/Catalina Probleme mit 20.2-Layout und Intel-HDMI-Ausgabe

### ISSUE THREAD

**Issue by rosperling** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#91]
Hallo Chris,

erstmal vielen Dank für Deine Bemühungen! Mein System läuft auch schon fast rund. Ich verwende das Gigabyte Z490 Vision D, einen i7-10700 und eine AMD RX570. Ich nutze zwei Bildschirme und habe zum Stromsparen den zweiten via Onboard-HDMI an die Intel IGFX angeschlossen. Dabei kommt es bei beiden System ab und zu zu Darstelungsfehlern (über beide Grafikkarten) in den Fenstern und zu unerklärlichen Abstürzen an aus meiner Sicht zufälligen Stellen (z.B. im APFS oder HFS-Modul).

Hast Du eine Idee?

Danke und Gruß,
Robert

**Comment by SchmockLord** [comment]
Ja. Disable mal die SSDT-5700.aml.

Und du solltest bei deiner CPU iMac20,1 verwenden und natürlich die config mit display output.

**Comment by rosperling** [comment]
Danke! Hab ich natürlich schon probiert. Gleiches Ergebnis.

Ich hab jetzt aber einen Zufallsfund gemacht. Wenn ich die IGFX als primär im BIOS setze, läuft alles wesentlich stabiler und ich habe keine Grafikfehler mehr. Nur das NVRAM muss ich noch von Zeit zu Zeit zurücksetzen, damit der Rechner bootet. Aber ansonsten bin ich schon recht glücklich mit dem Build. Ich bin jetzt auch auf den iMac20.1 umgestiegen, wobei sich mir der Unterschied immer noch nicht so recht erschließt - aber immerhin sieht es nun "echter" aus.

Vielen Dank für Deine Hilfe und tolle Vorlage!

**Comment by SchmockLord** [comment]
Danke Robert. Die Erfahrung die du beschreibst, hab ich auch gemacht. Also iGPU als Primary einzutragen.
