### ISSUE TITLE
The headphone and the internal-speakers cannot be switched automatically

### ISSUE THREAD

**Issue by stimw** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#94]
Hi Chris, thanks for your work.

My hardware is the same as yours, and everything goes well except that the headphone and the internal-speakers cannot be switched automatically.

I notice that the layout-id has been injected...

**Comment by mrtnnnn** [comment]
> Hi Chris, thanks for your work.
> 
> My hardware is the same as yours, and everything goes well except that the headphone and the internal-speakers cannot be switched automatically.
> 
> I notice that the layout-id has been injected...

Hi stimw,

have you been able to fix this? 
I tried out all of the possible layout-id's in the boot-args but this didn't fix it. 
The Headphone Jack only works with layout-id 28 and switches back from internal-speakers to headphones on every reboot.

**Comment by Nelbjo** [comment]
Same issue here - headphone jacket is switched back to primary audio output device on every reboot. Thx.

**Comment by stimw** [comment]
> > Hi Chris, thanks for your work.
> > My hardware is the same as yours, and everything goes well except that the headphone and the internal-speakers cannot be switched automatically.
> > I notice that the layout-id has been injected...
> 
> Hi stimw,
> 
> have you been able to fix this?
> I tried out all of the possible layout-id's in the boot-args but this didn't fix it.
> The Headphone Jack only works with layout-id 28 and switches back from internal-speakers to headphones on every reboot.

Not yet...

**Comment by Got99** [comment]
I  have this problem too
 headphones on every reboot.

**Comment by Got99** [comment]
if change other driver  , like voo....  ,it can solve this problem , but music is not good ....

**Comment by muzafferdede** [comment]
use layout id 7 instead of 11.
11 is for those who use front panel headphone jack

**Comment by mrtnnnn** [comment]
@stimw @Nelbjo 

I finally was able to solve this – at least for me.

With these changes to the config.plist macOS keeps the internal speakers as primary output after every reboot.
Also it switches to headphones automatically, when connected to the front audio panel headphone jack.

I don't know exactly which adjustments were decisive, but with these settings in the DeviceProperties + alcid=11 in the boot-args it works.

In the DeviceProperties Section:

			<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Internal@0,31,3</string>
				<key>device_type</key>
				<string>Audio device</string>
				<key>model</key>
				<string>Realtek 1220-VB</string>
			</dict>

In the boot-args I added `alcid=11`, did a NVRAM Reset and since then audio works as intended.

**Comment by Nelbjo** [comment]
@mrtnnnn many thanks - I tried this out yesterday after updating to latest OC 0.6.5 Release from @SchmockLord and it works!
I needed to change the device properties as you suggested and added alcid=11 in the boot-args. Works!

**Comment by mrtnnnn** [comment]
@Nelbjo Super, bin froh dass es noch jemandem hilft. :)

**Comment by SchmockLord** [comment]
@mrtnnnn Funktioniert denn sonst noch alles mit ALC-ID 11? Sprich hast du irgendwas festgestellt, was mit 11 nicht funktioniert aber mit der 28 funktioniert hat? Weil ansonsten nehm ich das in die config mit auf.

**Comment by mrtnnnn** [comment]
@SchmockLord Ich habe keinerlei Probleme seitdem ich die config so abgeändert habe feststellen können.Habe weiterhin Zugriff auf alles was unter 28 verfügbar war, außer dass jetzt alles wie es nativ auf einem Mac funktioniert läuft. 

Mir war wichtig dass die ALC-ID 11 nicht nur eine Kompromisslösung darstellt damit der primäre Audio Out erhalten bleibt sondern alles wirklich rund läuft.

Und vielen Dank an dieser Stelle für deine tolle Arbeit! :)

**Comment by SchmockLord** [comment]
Ok, danke für die Info. Dann committe ich das mal mit deinen changes! Danke dir!

**Comment by g3d** [comment]
Tested new commit, works well
